/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uibk.ac.at.smartcity.parser.antlr.internal.InternalSmartCityParser;
import uibk.ac.at.smartcity.services.SmartCityGrammarAccess;

public class SmartCityParser extends AbstractAntlrParser {

	@Inject
	private SmartCityGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmartCityParser createParser(XtextTokenStream stream) {
		return new InternalSmartCityParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SmartCityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartCityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
