/*
 * generated by Xtext 2.36.0
 */
package org.smartcitymodel.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.smartcitymodel.ui.internal.SmartcitymodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SmartcitymodelActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SmartcitymodelActivator activator = SmartcitymodelActivator.getInstance();
		return activator != null ? activator.getInjector(SmartcitymodelActivator.ORG_SMARTCITYMODEL_DSL) : null;
	}

}
