/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.validation

import java.io.File
import org.eclipse.xtext.validation.Check
import uibk.ac.at.smartcity.smartCity.CommunicationLink
import uibk.ac.at.smartcity.smartCity.Controller
import uibk.ac.at.smartcity.smartCity.DataGateway
import uibk.ac.at.smartcity.smartCity.DelayRange
import uibk.ac.at.smartcity.smartCity.Frequency
import uibk.ac.at.smartcity.smartCity.Model
import uibk.ac.at.smartcity.smartCity.Node
import uibk.ac.at.smartcity.smartCity.Sensor
import uibk.ac.at.smartcity.smartCity.SimulationProperties
import uibk.ac.at.smartcity.smartCity.SmartCityPackage

import static extension java.lang.Character.*
import uibk.ac.at.smartcity.smartCity.CyclicAction
import uibk.ac.at.smartcity.smartCity.TriggeredAction
import uibk.ac.at.smartcity.smartCity.ControllerType

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class SmartCityValidator extends AbstractSmartCityValidator {

	// Issue codes:
	protected static val ISSUE_CODE_PREFIX = "uibk.ac.at.smartcity."
	public static val INVALID_ENTITY_NAME = "InvalidEntityName"
	public static val INVALID_ATTRIBUTE_NAME = "InvalidAttributeName"

	// Naming conventions:
	// 1. Entities
	@Check
	def checkNodeStartsWithCapital(Node node) {
		if (node.name.charAt(0).lowerCase) {
			warning(
				"Node name should start with a capital",
				SmartCityPackage.Literals.LINKABLE__NAME,
				INVALID_ENTITY_NAME,
				node.name
			)
		}
	}

	@Check
	def checkDataGatewayStartsWithCapital(DataGateway dataGateway) {
		if (dataGateway.name.charAt(0).lowerCase) {
			warning(
				"DataGateway name should start with a capital",
				SmartCityPackage.Literals.LINKABLE__NAME,
				INVALID_ENTITY_NAME,
				dataGateway.name
			)
		}
	}

	// 2. Attributes
	// Check that all Node attribute names are lower case
	@Check
	def checkSensorNamesAreLowerCase(Sensor sensor) {
		if (sensor.name.charAt(0).upperCase) {
			warning(
				"Sensor name should start with a lower case letter",
				SmartCityPackage.Literals.LINKABLE__NAME,
				INVALID_ATTRIBUTE_NAME,
				sensor.name
			)
		}
	}

	@Check
	def checkModuleNamesAreLowerCase(Module module) {
		if (module.name.charAt(0).upperCase) {
			warning(
				"Module name should start with a lower case letter",
				SmartCityPackage.Literals.LINKABLE__NAME,
				INVALID_ATTRIBUTE_NAME,
				module.name
			)
		}
	}

	@Check
	def checkControllerNamesAreLowerCase(Controller controller) {
		if (controller.name.charAt(0).upperCase) {
			warning(
				"Controller name should start with a lower case letter",
				SmartCityPackage.Literals.LINKABLE__NAME,
				INVALID_ATTRIBUTE_NAME,
				controller.name
			)
		}
	}
	
	// Controller type
	@Check
	def checkControllerType(Controller controller) {
		if (controller.type == ControllerType.OTHER) {
			info(
			"For non-standard Controller types the pinout will not be inferred for constraint checking. They will still function as normal for the simulation.",
			SmartCityPackage.Literals.CONTROLLER__TYPE)
		}
	}

	// Simulation Properties checks:
	@Check
	def checkSimulationPropertiesNonNegativeTerminationTime(SimulationProperties props) {
		if (props.terminationTime <= 0) {
			error(
				"Termination Time for the simulation must be larger than 0",
				SmartCityPackage.Literals.SIMULATION_PROPERTIES__TERMINATION_TIME
			)
		}
	}

	@Check
	def checkSimulationPropertiesFileExists(SimulationProperties props) {
		if (!props.generatorFile.nullOrEmpty) {
			var f = new File(props.generatorFile)
			if (!f.exists() || f.isDirectory()) {
				error(
					"Can not find this File, please check the path",
					SmartCityPackage.Literals.SIMULATION_PROPERTIES__GENERATOR_FILE
				)
			} else if (!f.name.endsWith(".csv")) {
				error(
					"The Generator File must be of a 'csv' File",
					SmartCityPackage.Literals.SIMULATION_PROPERTIES__GENERATOR_FILE
				)
			}
		}
	}

	// Model checks:
	@Check
	def modelContainsAtLeastOneNode(Model model) {
		if (model.nodes.length < 1) {
			error(
				"The Model needs to contain at least one Node for the simulation",
				SmartCityPackage.Literals.MODEL__NODES
			)
		}
	}

	// Controller
	@Check
	def checkNodeBalance(Node node) {
		// Check if nodes are well-balanced (not too many sensors for controller type)
		switch (node.controller.type) {
			case ESP32: {
				if (node.sensors.size > 8) {
					warning("ESP32 controller might be overloaded with too many sensors", 
						SmartCityPackage.Literals.LINKABLE__NAME
					)
				}
			}
			case RASPBERRY_PI: {
				if (node.sensors.size > 16) {
					warning("Raspberry Pi controller might be overloaded with too many sensors", 
						SmartCityPackage.Literals.LINKABLE__NAME
					)
				}
			}
			default: {
			}
		}
	}

	// Delay Range:
	@Check
	def checkDelayRangeIsValid(DelayRange range) {
		if (range.max < range.min) {
			error(
				"Invalid Delay Range: Second value can not be smaller than the first",
				SmartCityPackage.Literals.DELAY_RANGE__MAX
			)
		}
	}

	@Check
	def checkDelayRangeNotNegative(DelayRange range) {
		if (range.min < 0) {
			error(
				"Delay minimum cannot be negative",
				SmartCityPackage.Literals.DELAY_RANGE__MIN
			)
		}
	}

	@Check
	def checkDelayRangeTooLarge(DelayRange range) {
		if (range.max > 100000) {
			warning(
				"Very high delay values may cause unrealistic simulation results",
				SmartCityPackage.Literals.DELAY_RANGE__MAX
			)
		}
	}

	// Frequency
	@Check
	def checkFrequencyNonNegative(Frequency frequency) {
		if (frequency.value <= 0) {
			error(
				"Frequency must be larger than 0",
				SmartCityPackage.Literals.FREQUENCY__VALUE
			)
		}
	}

	// Communication Links
	// If origin is a sensor the types must match, other cases where origin is a controller etc. do not require this check
	@Check
	def checkLinkDataTypeMatchesOriginIfSensor(CommunicationLink link) {
		val origin = link.origin
		if (origin instanceof Sensor) {
			if (origin.type != link.datatype) {
				error(
					"For links from sensors the link data type must match the sensor type",
					SmartCityPackage.Literals.COMMUNICATION_LINK__DATATYPE
				)
			}
		}
	}

	@Check
	def checkCommunicationLinkDuplicates(CommunicationLink link) {
		// First, get the containing Node
		val node = link.eContainer as Node

		if (node === null) {
			return
		}

		val duplicates = node.links.filter [ otherLink |
			// Skip comparison with itself
			otherLink !== link && // Check if origin, destination and datatype match
			otherLink.type == link.type && otherLink.origin == link.origin &&
				otherLink.destination == link.destination && otherLink.datatype == link.datatype
		]

		if (!duplicates.empty) {
			error(
				"Duplicate communication link", // both of the duplicates will show this message
				null
			)
		}
	}
	
	@Check
	def checkCommunicationLinkValidOrigin(CommunicationLink link) {
		if (link.origin instanceof Controller) {
			error("Controllers can't send data",
				SmartCityPackage.Literals.COMMUNICATION_LINK__ORIGIN
			)
		}
		else if (link.origin instanceof DataGateway) {
			error("The DataGateway can't send data",
				SmartCityPackage.Literals.COMMUNICATION_LINK__ORIGIN
			)
		}
	}
	
	@Check
	def checkCommunicationLinkValidDestination(CommunicationLink link) {
		if (link.destination instanceof Sensor) {
			error("Sensors can't receive data",
				SmartCityPackage.Literals.COMMUNICATION_LINK__DESTINATION
			)
		}
	}
	
	
	// Info for features that do not produce any Python Code yet
	@Check
	def checkCylicActionsHaveNotImplementedInfo(CyclicAction action){
		info(
		"Cyclic Actions are not yet implemented in the Code Generation, and will therefore have no effect for the simulation.",
		null
		)
	}
	
	@Check
	def checkTriggeredActionsHaveNotImplementedInfo(TriggeredAction action){
		info(
		"Triggered Actions are not yet implemented in the Code Generator, and will therefore have no effect for the simulation.",
		null
		)
	}
	
	@Check
	def checkModuleNotImplementedInfo(Module module) {
		info(
			"Modules are not yet implemented in the Code Generator, and will therefore have no effect for the simulation.",
			SmartCityPackage.Literals.LINKABLE__NAME
		)
	}
}
