/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmartCityScopeProvider extends DelegatingScopeProvider {
}
