/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uibk.ac.at.smartcity.SmartCityRuntimeModule;
import uibk.ac.at.smartcity.SmartCityStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SmartCityIdeSetup extends SmartCityStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SmartCityRuntimeModule(), new SmartCityIdeModule()));
	}
	
}
