/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SmartCityGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNodesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNodesNodeParserRuleCall_0_0 = (RuleCall)cNodesAssignment_0.eContents().get(0);
		private final Assignment cInteroperableLayerAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInteroperableLayerLayerParserRuleCall_1_0 = (RuleCall)cInteroperableLayerAssignment_1.eContents().get(0);
		private final Assignment cGlobalLinksAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cGlobalLinksCommunicationLinkParserRuleCall_2_0 = (RuleCall)cGlobalLinksAssignment_2.eContents().get(0);
		
		//Model:
		//    nodes+=Node*
		//    interoperableLayer=Layer
		//    globalLinks+=CommunicationLink*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//nodes+=Node*
		//interoperableLayer=Layer
		//globalLinks+=CommunicationLink*
		public Group getGroup() { return cGroup; }
		
		//nodes+=Node*
		public Assignment getNodesAssignment_0() { return cNodesAssignment_0; }
		
		//Node
		public RuleCall getNodesNodeParserRuleCall_0_0() { return cNodesNodeParserRuleCall_0_0; }
		
		//interoperableLayer=Layer
		public Assignment getInteroperableLayerAssignment_1() { return cInteroperableLayerAssignment_1; }
		
		//Layer
		public RuleCall getInteroperableLayerLayerParserRuleCall_1_0() { return cInteroperableLayerLayerParserRuleCall_1_0; }
		
		//globalLinks+=CommunicationLink*
		public Assignment getGlobalLinksAssignment_2() { return cGlobalLinksAssignment_2; }
		
		//CommunicationLink
		public RuleCall getGlobalLinksCommunicationLinkParserRuleCall_2_0() { return cGlobalLinksCommunicationLinkParserRuleCall_2_0; }
	}
	public class LayerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.Layer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLayerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cPriorityKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPriorityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPriorityINTTerminalRuleCall_3_0 = (RuleCall)cPriorityAssignment_3.eContents().get(0);
		private final Keyword cDelayKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDelayAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDelayINTTerminalRuleCall_5_0 = (RuleCall)cDelayAssignment_5.eContents().get(0);
		
		//Layer:
		//    'layer' name=ID
		//    'priority' priority=INT
		//    'delay' delay=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'layer' name=ID
		//'priority' priority=INT
		//'delay' delay=INT
		public Group getGroup() { return cGroup; }
		
		//'layer'
		public Keyword getLayerKeyword_0() { return cLayerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'priority'
		public Keyword getPriorityKeyword_2() { return cPriorityKeyword_2; }
		
		//priority=INT
		public Assignment getPriorityAssignment_3() { return cPriorityAssignment_3; }
		
		//INT
		public RuleCall getPriorityINTTerminalRuleCall_3_0() { return cPriorityINTTerminalRuleCall_3_0; }
		
		//'delay'
		public Keyword getDelayKeyword_4() { return cDelayKeyword_4; }
		
		//delay=INT
		public Assignment getDelayAssignment_5() { return cDelayAssignment_5; }
		
		//INT
		public RuleCall getDelayINTTerminalRuleCall_5_0() { return cDelayINTTerminalRuleCall_5_0; }
	}
	public class NodeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.Node");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNodeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSensorsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSensorsSensorParserRuleCall_3_0 = (RuleCall)cSensorsAssignment_3.eContents().get(0);
		private final Assignment cControllerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cControllerControllerParserRuleCall_4_0 = (RuleCall)cControllerAssignment_4.eContents().get(0);
		private final Assignment cLinksAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLinksCommunicationLinkParserRuleCall_5_0 = (RuleCall)cLinksAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Node:
		//    'node' name=ID
		//    '{'
		//        sensors+=Sensor*
		//        controller=Controller
		//        links+=CommunicationLink*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'node' name=ID
		//'{'
		//    sensors+=Sensor*
		//    controller=Controller
		//    links+=CommunicationLink*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'node'
		public Keyword getNodeKeyword_0() { return cNodeKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//sensors+=Sensor*
		public Assignment getSensorsAssignment_3() { return cSensorsAssignment_3; }
		
		//Sensor
		public RuleCall getSensorsSensorParserRuleCall_3_0() { return cSensorsSensorParserRuleCall_3_0; }
		
		//controller=Controller
		public Assignment getControllerAssignment_4() { return cControllerAssignment_4; }
		
		//Controller
		public RuleCall getControllerControllerParserRuleCall_4_0() { return cControllerControllerParserRuleCall_4_0; }
		
		//links+=CommunicationLink*
		public Assignment getLinksAssignment_5() { return cLinksAssignment_5; }
		
		//CommunicationLink
		public RuleCall getLinksCommunicationLinkParserRuleCall_5_0() { return cLinksCommunicationLinkParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class SensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.Sensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSensorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeSensorTypeEnumRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final Keyword cPriorityKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPriorityAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPriorityINTTerminalRuleCall_5_0 = (RuleCall)cPriorityAssignment_5.eContents().get(0);
		
		//Sensor:
		//    'sensor' name=ID
		//    'type' type=SensorType
		//    'priority' priority=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'sensor' name=ID
		//'type' type=SensorType
		//'priority' priority=INT
		public Group getGroup() { return cGroup; }
		
		//'sensor'
		public Keyword getSensorKeyword_0() { return cSensorKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//type=SensorType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }
		
		//SensorType
		public RuleCall getTypeSensorTypeEnumRuleCall_3_0() { return cTypeSensorTypeEnumRuleCall_3_0; }
		
		//'priority'
		public Keyword getPriorityKeyword_4() { return cPriorityKeyword_4; }
		
		//priority=INT
		public Assignment getPriorityAssignment_5() { return cPriorityAssignment_5; }
		
		//INT
		public RuleCall getPriorityINTTerminalRuleCall_5_0() { return cPriorityINTTerminalRuleCall_5_0; }
	}
	public class CommunicationLinkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.CommunicationLink");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLinkKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeLinkTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Keyword cFromKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOriginAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cOriginLinkableCrossReference_3_0 = (CrossReference)cOriginAssignment_3.eContents().get(0);
		private final RuleCall cOriginLinkableIDTerminalRuleCall_3_0_1 = (RuleCall)cOriginLinkableCrossReference_3_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDestinationAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cDestinationLinkableCrossReference_5_0 = (CrossReference)cDestinationAssignment_5.eContents().get(0);
		private final RuleCall cDestinationLinkableIDTerminalRuleCall_5_0_1 = (RuleCall)cDestinationLinkableCrossReference_5_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cDelayKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDelayAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDelayDelayRangeParserRuleCall_8_0 = (RuleCall)cDelayAssignment_8.eContents().get(0);
		private final Keyword cDatatypeKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDatatypeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDatatypeDataTypeEnumRuleCall_10_0 = (RuleCall)cDatatypeAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//CommunicationLink:
		//    'link' type=LinkType 'from' origin=[Linkable] '->' destination=[Linkable] '{'
		//        'delay' delay=DelayRange
		//        'datatype' datatype=DataType
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'link' type=LinkType 'from' origin=[Linkable] '->' destination=[Linkable] '{'
		//    'delay' delay=DelayRange
		//    'datatype' datatype=DataType
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'link'
		public Keyword getLinkKeyword_0() { return cLinkKeyword_0; }
		
		//type=LinkType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//LinkType
		public RuleCall getTypeLinkTypeEnumRuleCall_1_0() { return cTypeLinkTypeEnumRuleCall_1_0; }
		
		//'from'
		public Keyword getFromKeyword_2() { return cFromKeyword_2; }
		
		//origin=[Linkable]
		public Assignment getOriginAssignment_3() { return cOriginAssignment_3; }
		
		//[Linkable]
		public CrossReference getOriginLinkableCrossReference_3_0() { return cOriginLinkableCrossReference_3_0; }
		
		//ID
		public RuleCall getOriginLinkableIDTerminalRuleCall_3_0_1() { return cOriginLinkableIDTerminalRuleCall_3_0_1; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_4() { return cHyphenMinusGreaterThanSignKeyword_4; }
		
		//destination=[Linkable]
		public Assignment getDestinationAssignment_5() { return cDestinationAssignment_5; }
		
		//[Linkable]
		public CrossReference getDestinationLinkableCrossReference_5_0() { return cDestinationLinkableCrossReference_5_0; }
		
		//ID
		public RuleCall getDestinationLinkableIDTerminalRuleCall_5_0_1() { return cDestinationLinkableIDTerminalRuleCall_5_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//'delay'
		public Keyword getDelayKeyword_7() { return cDelayKeyword_7; }
		
		//delay=DelayRange
		public Assignment getDelayAssignment_8() { return cDelayAssignment_8; }
		
		//DelayRange
		public RuleCall getDelayDelayRangeParserRuleCall_8_0() { return cDelayDelayRangeParserRuleCall_8_0; }
		
		//'datatype'
		public Keyword getDatatypeKeyword_9() { return cDatatypeKeyword_9; }
		
		//datatype=DataType
		public Assignment getDatatypeAssignment_10() { return cDatatypeAssignment_10; }
		
		//DataType
		public RuleCall getDatatypeDataTypeEnumRuleCall_10_0() { return cDatatypeDataTypeEnumRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ControllerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.Controller");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cControllerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Controller:
		//    'controller' name=ID
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'controller' name=ID
		public Group getGroup() { return cGroup; }
		
		//'controller'
		public Keyword getControllerKeyword_0() { return cControllerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class LinkableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.Linkable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cControllerParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSensorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLayerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNodeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Linkable:
		//    Controller | Sensor | Layer | Node
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Controller | Sensor | Layer | Node
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Controller
		public RuleCall getControllerParserRuleCall_0() { return cControllerParserRuleCall_0; }
		
		//Sensor
		public RuleCall getSensorParserRuleCall_1() { return cSensorParserRuleCall_1; }
		
		//Layer
		public RuleCall getLayerParserRuleCall_2() { return cLayerParserRuleCall_2; }
		
		//Node
		public RuleCall getNodeParserRuleCall_3() { return cNodeParserRuleCall_3; }
	}
	public class DelayRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.DelayRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMinAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMinINTTerminalRuleCall_1_0 = (RuleCall)cMinAssignment_1.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMaxAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMaxINTTerminalRuleCall_3_0 = (RuleCall)cMaxAssignment_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//DelayRange:
		//    '[' min=INT '..' max=INT ']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'[' min=INT '..' max=INT ']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//min=INT
		public Assignment getMinAssignment_1() { return cMinAssignment_1; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_1_0() { return cMinINTTerminalRuleCall_1_0; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_2() { return cFullStopFullStopKeyword_2; }
		
		//max=INT
		public Assignment getMaxAssignment_3() { return cMaxAssignment_3; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_3_0() { return cMaxINTTerminalRuleCall_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }
	}
	
	public class SensorTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.SensorType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTEMPERATUREEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTEMPERATURETEMPERATUREKeyword_0_0 = (Keyword)cTEMPERATUREEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPHEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPHPHKeyword_1_0 = (Keyword)cPHEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTURBIDITYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTURBIDITYTURBIDITYKeyword_2_0 = (Keyword)cTURBIDITYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cTDSEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cTDSTDSKeyword_3_0 = (Keyword)cTDSEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCURRENTEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCURRENTCURRENTKeyword_4_0 = (Keyword)cCURRENTEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cPULSEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cPULSEPULSEKeyword_5_0 = (Keyword)cPULSEEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cULTRASONICEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cULTRASONICULTRASONICKeyword_6_0 = (Keyword)cULTRASONICEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCAMERAEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCAMERACAMERAKeyword_7_0 = (Keyword)cCAMERAEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum SensorType:
		//    TEMPERATURE | PH | TURBIDITY | TDS | CURRENT | PULSE | ULTRASONIC | CAMERA
		//;
		public EnumRule getRule() { return rule; }
		
		//TEMPERATURE | PH | TURBIDITY | TDS | CURRENT | PULSE | ULTRASONIC | CAMERA
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TEMPERATURE
		public EnumLiteralDeclaration getTEMPERATUREEnumLiteralDeclaration_0() { return cTEMPERATUREEnumLiteralDeclaration_0; }
		
		public Keyword getTEMPERATURETEMPERATUREKeyword_0_0() { return cTEMPERATURETEMPERATUREKeyword_0_0; }
		
		//PH
		public EnumLiteralDeclaration getPHEnumLiteralDeclaration_1() { return cPHEnumLiteralDeclaration_1; }
		
		public Keyword getPHPHKeyword_1_0() { return cPHPHKeyword_1_0; }
		
		//TURBIDITY
		public EnumLiteralDeclaration getTURBIDITYEnumLiteralDeclaration_2() { return cTURBIDITYEnumLiteralDeclaration_2; }
		
		public Keyword getTURBIDITYTURBIDITYKeyword_2_0() { return cTURBIDITYTURBIDITYKeyword_2_0; }
		
		//TDS
		public EnumLiteralDeclaration getTDSEnumLiteralDeclaration_3() { return cTDSEnumLiteralDeclaration_3; }
		
		public Keyword getTDSTDSKeyword_3_0() { return cTDSTDSKeyword_3_0; }
		
		//CURRENT
		public EnumLiteralDeclaration getCURRENTEnumLiteralDeclaration_4() { return cCURRENTEnumLiteralDeclaration_4; }
		
		public Keyword getCURRENTCURRENTKeyword_4_0() { return cCURRENTCURRENTKeyword_4_0; }
		
		//PULSE
		public EnumLiteralDeclaration getPULSEEnumLiteralDeclaration_5() { return cPULSEEnumLiteralDeclaration_5; }
		
		public Keyword getPULSEPULSEKeyword_5_0() { return cPULSEPULSEKeyword_5_0; }
		
		//ULTRASONIC
		public EnumLiteralDeclaration getULTRASONICEnumLiteralDeclaration_6() { return cULTRASONICEnumLiteralDeclaration_6; }
		
		public Keyword getULTRASONICULTRASONICKeyword_6_0() { return cULTRASONICULTRASONICKeyword_6_0; }
		
		//CAMERA
		public EnumLiteralDeclaration getCAMERAEnumLiteralDeclaration_7() { return cCAMERAEnumLiteralDeclaration_7; }
		
		public Keyword getCAMERACAMERAKeyword_7_0() { return cCAMERACAMERAKeyword_7_0; }
	}
	public class LinkTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.LinkType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUARTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUARTUARTKeyword_0_0 = (Keyword)cUARTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cADCEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cADCADCKeyword_1_0 = (Keyword)cADCEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSPIEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSPISPIKeyword_2_0 = (Keyword)cSPIEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cGPIOEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cGPIOGPIOKeyword_3_0 = (Keyword)cGPIOEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCSIEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCSICSIKeyword_4_0 = (Keyword)cCSIEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cHTTPSEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cHTTPSHTTPSKeyword_5_0 = (Keyword)cHTTPSEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum LinkType:
		//    UART | ADC | SPI | GPIO | CSI | HTTPS
		//;
		public EnumRule getRule() { return rule; }
		
		//UART | ADC | SPI | GPIO | CSI | HTTPS
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//UART
		public EnumLiteralDeclaration getUARTEnumLiteralDeclaration_0() { return cUARTEnumLiteralDeclaration_0; }
		
		public Keyword getUARTUARTKeyword_0_0() { return cUARTUARTKeyword_0_0; }
		
		//ADC
		public EnumLiteralDeclaration getADCEnumLiteralDeclaration_1() { return cADCEnumLiteralDeclaration_1; }
		
		public Keyword getADCADCKeyword_1_0() { return cADCADCKeyword_1_0; }
		
		//SPI
		public EnumLiteralDeclaration getSPIEnumLiteralDeclaration_2() { return cSPIEnumLiteralDeclaration_2; }
		
		public Keyword getSPISPIKeyword_2_0() { return cSPISPIKeyword_2_0; }
		
		//GPIO
		public EnumLiteralDeclaration getGPIOEnumLiteralDeclaration_3() { return cGPIOEnumLiteralDeclaration_3; }
		
		public Keyword getGPIOGPIOKeyword_3_0() { return cGPIOGPIOKeyword_3_0; }
		
		//CSI
		public EnumLiteralDeclaration getCSIEnumLiteralDeclaration_4() { return cCSIEnumLiteralDeclaration_4; }
		
		public Keyword getCSICSIKeyword_4_0() { return cCSICSIKeyword_4_0; }
		
		//HTTPS
		public EnumLiteralDeclaration getHTTPSEnumLiteralDeclaration_5() { return cHTTPSEnumLiteralDeclaration_5; }
		
		public Keyword getHTTPSHTTPSKeyword_5_0() { return cHTTPSHTTPSKeyword_5_0; }
	}
	public class DataTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uibk.ac.at.smartcity.SmartCity.DataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPHEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPHPHKeyword_0_0 = (Keyword)cPHEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTDSEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTDSTDSKeyword_1_0 = (Keyword)cTDSEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTEMPERATUREEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTEMPERATURETEMPERATUREKeyword_2_0 = (Keyword)cTEMPERATUREEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum DataType:
		//    PH | TDS | TEMPERATURE
		//;
		public EnumRule getRule() { return rule; }
		
		//PH | TDS | TEMPERATURE
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PH
		public EnumLiteralDeclaration getPHEnumLiteralDeclaration_0() { return cPHEnumLiteralDeclaration_0; }
		
		public Keyword getPHPHKeyword_0_0() { return cPHPHKeyword_0_0; }
		
		//TDS
		public EnumLiteralDeclaration getTDSEnumLiteralDeclaration_1() { return cTDSEnumLiteralDeclaration_1; }
		
		public Keyword getTDSTDSKeyword_1_0() { return cTDSTDSKeyword_1_0; }
		
		//TEMPERATURE
		public EnumLiteralDeclaration getTEMPERATUREEnumLiteralDeclaration_2() { return cTEMPERATUREEnumLiteralDeclaration_2; }
		
		public Keyword getTEMPERATURETEMPERATUREKeyword_2_0() { return cTEMPERATURETEMPERATUREKeyword_2_0; }
	}
	
	private final ModelElements pModel;
	private final LayerElements pLayer;
	private final NodeElements pNode;
	private final SensorElements pSensor;
	private final CommunicationLinkElements pCommunicationLink;
	private final ControllerElements pController;
	private final LinkableElements pLinkable;
	private final DelayRangeElements pDelayRange;
	private final SensorTypeElements eSensorType;
	private final LinkTypeElements eLinkType;
	private final DataTypeElements eDataType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmartCityGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pLayer = new LayerElements();
		this.pNode = new NodeElements();
		this.pSensor = new SensorElements();
		this.pCommunicationLink = new CommunicationLinkElements();
		this.pController = new ControllerElements();
		this.pLinkable = new LinkableElements();
		this.pDelayRange = new DelayRangeElements();
		this.eSensorType = new SensorTypeElements();
		this.eLinkType = new LinkTypeElements();
		this.eDataType = new DataTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uibk.ac.at.smartcity.SmartCity".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    nodes+=Node*
	//    interoperableLayer=Layer
	//    globalLinks+=CommunicationLink*
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Layer:
	//    'layer' name=ID
	//    'priority' priority=INT
	//    'delay' delay=INT
	//;
	public LayerElements getLayerAccess() {
		return pLayer;
	}
	
	public ParserRule getLayerRule() {
		return getLayerAccess().getRule();
	}
	
	//Node:
	//    'node' name=ID
	//    '{'
	//        sensors+=Sensor*
	//        controller=Controller
	//        links+=CommunicationLink*
	//    '}'
	//;
	public NodeElements getNodeAccess() {
		return pNode;
	}
	
	public ParserRule getNodeRule() {
		return getNodeAccess().getRule();
	}
	
	//Sensor:
	//    'sensor' name=ID
	//    'type' type=SensorType
	//    'priority' priority=INT
	//;
	public SensorElements getSensorAccess() {
		return pSensor;
	}
	
	public ParserRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//CommunicationLink:
	//    'link' type=LinkType 'from' origin=[Linkable] '->' destination=[Linkable] '{'
	//        'delay' delay=DelayRange
	//        'datatype' datatype=DataType
	//    '}'
	//;
	public CommunicationLinkElements getCommunicationLinkAccess() {
		return pCommunicationLink;
	}
	
	public ParserRule getCommunicationLinkRule() {
		return getCommunicationLinkAccess().getRule();
	}
	
	//Controller:
	//    'controller' name=ID
	//;
	public ControllerElements getControllerAccess() {
		return pController;
	}
	
	public ParserRule getControllerRule() {
		return getControllerAccess().getRule();
	}
	
	//Linkable:
	//    Controller | Sensor | Layer | Node
	//;
	public LinkableElements getLinkableAccess() {
		return pLinkable;
	}
	
	public ParserRule getLinkableRule() {
		return getLinkableAccess().getRule();
	}
	
	//DelayRange:
	//    '[' min=INT '..' max=INT ']'
	//;
	public DelayRangeElements getDelayRangeAccess() {
		return pDelayRange;
	}
	
	public ParserRule getDelayRangeRule() {
		return getDelayRangeAccess().getRule();
	}
	
	//enum SensorType:
	//    TEMPERATURE | PH | TURBIDITY | TDS | CURRENT | PULSE | ULTRASONIC | CAMERA
	//;
	public SensorTypeElements getSensorTypeAccess() {
		return eSensorType;
	}
	
	public EnumRule getSensorTypeRule() {
		return getSensorTypeAccess().getRule();
	}
	
	//enum LinkType:
	//    UART | ADC | SPI | GPIO | CSI | HTTPS
	//;
	public LinkTypeElements getLinkTypeAccess() {
		return eLinkType;
	}
	
	public EnumRule getLinkTypeRule() {
		return getLinkTypeAccess().getRule();
	}
	
	//enum DataType:
	//    PH | TDS | TEMPERATURE
	//;
	public DataTypeElements getDataTypeAccess() {
		return eDataType;
	}
	
	public EnumRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
