/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Controller</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getController()
 * @model
 * @generated
 */
public interface Controller extends Linkable
{
} // Controller
