/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Controller</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Controller#getType <em>Type</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Controller#getCyclicActions <em>Cyclic Actions</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Controller#getTriggeredActions <em>Triggered Actions</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getController()
 * @model
 * @generated
 */
public interface Controller extends Linkable
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link uibk.ac.at.smartcity.smartCity.ControllerType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.ControllerType
   * @see #setType(ControllerType)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getController_Type()
   * @model
   * @generated
   */
  ControllerType getType();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Controller#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.ControllerType
   * @see #getType()
   * @generated
   */
  void setType(ControllerType value);

  /**
   * Returns the value of the '<em><b>Cyclic Actions</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.smartcity.smartCity.CyclicAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cyclic Actions</em>' containment reference list.
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getController_CyclicActions()
   * @model containment="true"
   * @generated
   */
  EList<CyclicAction> getCyclicActions();

  /**
   * Returns the value of the '<em><b>Triggered Actions</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.smartcity.smartCity.TriggeredAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triggered Actions</em>' containment reference list.
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getController_TriggeredActions()
   * @model containment="true"
   * @generated
   */
  EList<TriggeredAction> getTriggeredActions();

} // Controller
