/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cyclic Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.CyclicAction#getName <em>Name</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.CyclicAction#getFreqValue <em>Freq Value</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.CyclicAction#getFreqUnit <em>Freq Unit</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getCyclicAction()
 * @model
 * @generated
 */
public interface CyclicAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getCyclicAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.CyclicAction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Freq Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Freq Value</em>' attribute.
   * @see #setFreqValue(int)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getCyclicAction_FreqValue()
   * @model
   * @generated
   */
  int getFreqValue();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.CyclicAction#getFreqValue <em>Freq Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Freq Value</em>' attribute.
   * @see #getFreqValue()
   * @generated
   */
  void setFreqValue(int value);

  /**
   * Returns the value of the '<em><b>Freq Unit</b></em>' attribute.
   * The literals are from the enumeration {@link uibk.ac.at.smartcity.smartCity.FrequencyUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Freq Unit</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.FrequencyUnit
   * @see #setFreqUnit(FrequencyUnit)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getCyclicAction_FreqUnit()
   * @model
   * @generated
   */
  FrequencyUnit getFreqUnit();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.CyclicAction#getFreqUnit <em>Freq Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Freq Unit</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.FrequencyUnit
   * @see #getFreqUnit()
   * @generated
   */
  void setFreqUnit(FrequencyUnit value);

} // CyclicAction
