/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frequency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Frequency#getValue <em>Value</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Frequency#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getFrequency()
 * @model
 * @generated
 */
public interface Frequency extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getFrequency_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Frequency#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link uibk.ac.at.smartcity.smartCity.FrequencyUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.FrequencyUnit
   * @see #setUnit(FrequencyUnit)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getFrequency_Unit()
   * @model
   * @generated
   */
  FrequencyUnit getUnit();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Frequency#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.FrequencyUnit
   * @see #getUnit()
   * @generated
   */
  void setUnit(FrequencyUnit value);

} // Frequency
