/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Node#getSensors <em>Sensors</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Node#getModules <em>Modules</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Node#getController <em>Controller</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Node#getLinks <em>Links</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Node#getFrequency <em>Frequency</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends Linkable
{
  /**
   * Returns the value of the '<em><b>Sensors</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.smartcity.smartCity.Sensor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensors</em>' containment reference list.
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getNode_Sensors()
   * @model containment="true"
   * @generated
   */
  EList<Sensor> getSensors();

  /**
   * Returns the value of the '<em><b>Modules</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.smartcity.smartCity.Module}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modules</em>' containment reference list.
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getNode_Modules()
   * @model containment="true"
   * @generated
   */
  EList<uibk.ac.at.smartcity.smartCity.Module> getModules();

  /**
   * Returns the value of the '<em><b>Controller</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller</em>' containment reference.
   * @see #setController(Controller)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getNode_Controller()
   * @model containment="true"
   * @generated
   */
  Controller getController();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Node#getController <em>Controller</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller</em>' containment reference.
   * @see #getController()
   * @generated
   */
  void setController(Controller value);

  /**
   * Returns the value of the '<em><b>Links</b></em>' containment reference list.
   * The list contents are of type {@link uibk.ac.at.smartcity.smartCity.CommunicationLink}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links</em>' containment reference list.
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getNode_Links()
   * @model containment="true"
   * @generated
   */
  EList<CommunicationLink> getLinks();

  /**
   * Returns the value of the '<em><b>Frequency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Frequency</em>' containment reference.
   * @see #setFrequency(Frequency)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getNode_Frequency()
   * @model containment="true"
   * @generated
   */
  Frequency getFrequency();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Node#getFrequency <em>Frequency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Frequency</em>' containment reference.
   * @see #getFrequency()
   * @generated
   */
  void setFrequency(Frequency value);

} // Node
