/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Sensor#getType <em>Type</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.Sensor#getPriority <em>Priority</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends Linkable
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link uibk.ac.at.smartcity.smartCity.SensorType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.SensorType
   * @see #setType(SensorType)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getSensor_Type()
   * @model
   * @generated
   */
  SensorType getType();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Sensor#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see uibk.ac.at.smartcity.smartCity.SensorType
   * @see #getType()
   * @generated
   */
  void setType(SensorType value);

  /**
   * Returns the value of the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Priority</em>' attribute.
   * @see #setPriority(int)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getSensor_Priority()
   * @model
   * @generated
   */
  int getPriority();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.Sensor#getPriority <em>Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Priority</em>' attribute.
   * @see #getPriority()
   * @generated
   */
  void setPriority(int value);

} // Sensor
