/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simulation Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.SimulationProperties#getTerminationTime <em>Termination Time</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.SimulationProperties#getGeneratorFile <em>Generator File</em>}</li>
 * </ul>
 *
 * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getSimulationProperties()
 * @model
 * @generated
 */
public interface SimulationProperties extends EObject
{
  /**
   * Returns the value of the '<em><b>Termination Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termination Time</em>' attribute.
   * @see #setTerminationTime(int)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getSimulationProperties_TerminationTime()
   * @model
   * @generated
   */
  int getTerminationTime();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.SimulationProperties#getTerminationTime <em>Termination Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Termination Time</em>' attribute.
   * @see #getTerminationTime()
   * @generated
   */
  void setTerminationTime(int value);

  /**
   * Returns the value of the '<em><b>Generator File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generator File</em>' attribute.
   * @see #setGeneratorFile(String)
   * @see uibk.ac.at.smartcity.smartCity.SmartCityPackage#getSimulationProperties_GeneratorFile()
   * @model
   * @generated
   */
  String getGeneratorFile();

  /**
   * Sets the value of the '{@link uibk.ac.at.smartcity.smartCity.SimulationProperties#getGeneratorFile <em>Generator File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generator File</em>' attribute.
   * @see #getGeneratorFile()
   * @generated
   */
  void setGeneratorFile(String value);

} // SimulationProperties
