/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uibk.ac.at.smartcity.smartCity.SmartCityFactory
 * @model kind="package"
 * @generated
 */
public interface SmartCityPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "smartCity";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uibk/at/smartcity/SmartCity";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "smartCity";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SmartCityPackage eINSTANCE = uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl.init();

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.ModelImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NODES = 0;

  /**
   * The feature id for the '<em><b>Interoperable Layer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INTEROPERABLE_LAYER = 1;

  /**
   * The feature id for the '<em><b>Global Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GLOBAL_LINKS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.LinkableImpl <em>Linkable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.LinkableImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getLinkable()
   * @generated
   */
  int LINKABLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Linkable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINKABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.LayerImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__NAME = LINKABLE__NAME;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__PRIORITY = LINKABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Delay</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__DELAY = LINKABLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = LINKABLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.NodeImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getNode()
   * @generated
   */
  int NODE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = LINKABLE__NAME;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__SENSORS = LINKABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Controller</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__CONTROLLER = LINKABLE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Links</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__LINKS = LINKABLE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = LINKABLE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.SensorImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = LINKABLE__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TYPE = LINKABLE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__PRIORITY = LINKABLE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = LINKABLE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.CommunicationLinkImpl <em>Communication Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.CommunicationLinkImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getCommunicationLink()
   * @generated
   */
  int COMMUNICATION_LINK = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_LINK__TYPE = 0;

  /**
   * The feature id for the '<em><b>Origin</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_LINK__ORIGIN = 1;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_LINK__DESTINATION = 2;

  /**
   * The feature id for the '<em><b>Delay</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_LINK__DELAY = 3;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_LINK__DATATYPE = 4;

  /**
   * The number of structural features of the '<em>Communication Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_LINK_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.ControllerImpl <em>Controller</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.ControllerImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getController()
   * @generated
   */
  int CONTROLLER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__NAME = LINKABLE__NAME;

  /**
   * The number of structural features of the '<em>Controller</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER_FEATURE_COUNT = LINKABLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.impl.DelayRangeImpl <em>Delay Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.impl.DelayRangeImpl
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getDelayRange()
   * @generated
   */
  int DELAY_RANGE = 7;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAY_RANGE__MIN = 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAY_RANGE__MAX = 1;

  /**
   * The number of structural features of the '<em>Delay Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DELAY_RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.SensorType <em>Sensor Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.SensorType
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getSensorType()
   * @generated
   */
  int SENSOR_TYPE = 8;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.LinkType <em>Link Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.LinkType
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getLinkType()
   * @generated
   */
  int LINK_TYPE = 9;

  /**
   * The meta object id for the '{@link uibk.ac.at.smartcity.smartCity.DataType <em>Data Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uibk.ac.at.smartcity.smartCity.DataType
   * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 10;


  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.smartcity.smartCity.Model#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Model#getNodes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Nodes();

  /**
   * Returns the meta object for the containment reference '{@link uibk.ac.at.smartcity.smartCity.Model#getInteroperableLayer <em>Interoperable Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Interoperable Layer</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Model#getInteroperableLayer()
   * @see #getModel()
   * @generated
   */
  EReference getModel_InteroperableLayer();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.smartcity.smartCity.Model#getGlobalLinks <em>Global Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Global Links</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Model#getGlobalLinks()
   * @see #getModel()
   * @generated
   */
  EReference getModel_GlobalLinks();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.Layer#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Layer#getPriority()
   * @see #getLayer()
   * @generated
   */
  EAttribute getLayer_Priority();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.Layer#getDelay <em>Delay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delay</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Layer#getDelay()
   * @see #getLayer()
   * @generated
   */
  EAttribute getLayer_Delay();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.smartcity.smartCity.Node#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Node#getSensors()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Sensors();

  /**
   * Returns the meta object for the containment reference '{@link uibk.ac.at.smartcity.smartCity.Node#getController <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Controller</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Node#getController()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Controller();

  /**
   * Returns the meta object for the containment reference list '{@link uibk.ac.at.smartcity.smartCity.Node#getLinks <em>Links</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Links</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Node#getLinks()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Links();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.Sensor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Sensor#getType()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Type();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.Sensor#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Priority</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Sensor#getPriority()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Priority();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.CommunicationLink <em>Communication Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Communication Link</em>'.
   * @see uibk.ac.at.smartcity.smartCity.CommunicationLink
   * @generated
   */
  EClass getCommunicationLink();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.CommunicationLink#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see uibk.ac.at.smartcity.smartCity.CommunicationLink#getType()
   * @see #getCommunicationLink()
   * @generated
   */
  EAttribute getCommunicationLink_Type();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.smartcity.smartCity.CommunicationLink#getOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Origin</em>'.
   * @see uibk.ac.at.smartcity.smartCity.CommunicationLink#getOrigin()
   * @see #getCommunicationLink()
   * @generated
   */
  EReference getCommunicationLink_Origin();

  /**
   * Returns the meta object for the reference '{@link uibk.ac.at.smartcity.smartCity.CommunicationLink#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see uibk.ac.at.smartcity.smartCity.CommunicationLink#getDestination()
   * @see #getCommunicationLink()
   * @generated
   */
  EReference getCommunicationLink_Destination();

  /**
   * Returns the meta object for the containment reference '{@link uibk.ac.at.smartcity.smartCity.CommunicationLink#getDelay <em>Delay</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Delay</em>'.
   * @see uibk.ac.at.smartcity.smartCity.CommunicationLink#getDelay()
   * @see #getCommunicationLink()
   * @generated
   */
  EReference getCommunicationLink_Delay();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.CommunicationLink#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datatype</em>'.
   * @see uibk.ac.at.smartcity.smartCity.CommunicationLink#getDatatype()
   * @see #getCommunicationLink()
   * @generated
   */
  EAttribute getCommunicationLink_Datatype();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.Controller <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Controller</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Controller
   * @generated
   */
  EClass getController();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.Linkable <em>Linkable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Linkable</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Linkable
   * @generated
   */
  EClass getLinkable();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.Linkable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uibk.ac.at.smartcity.smartCity.Linkable#getName()
   * @see #getLinkable()
   * @generated
   */
  EAttribute getLinkable_Name();

  /**
   * Returns the meta object for class '{@link uibk.ac.at.smartcity.smartCity.DelayRange <em>Delay Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Delay Range</em>'.
   * @see uibk.ac.at.smartcity.smartCity.DelayRange
   * @generated
   */
  EClass getDelayRange();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.DelayRange#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see uibk.ac.at.smartcity.smartCity.DelayRange#getMin()
   * @see #getDelayRange()
   * @generated
   */
  EAttribute getDelayRange_Min();

  /**
   * Returns the meta object for the attribute '{@link uibk.ac.at.smartcity.smartCity.DelayRange#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see uibk.ac.at.smartcity.smartCity.DelayRange#getMax()
   * @see #getDelayRange()
   * @generated
   */
  EAttribute getDelayRange_Max();

  /**
   * Returns the meta object for enum '{@link uibk.ac.at.smartcity.smartCity.SensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Sensor Type</em>'.
   * @see uibk.ac.at.smartcity.smartCity.SensorType
   * @generated
   */
  EEnum getSensorType();

  /**
   * Returns the meta object for enum '{@link uibk.ac.at.smartcity.smartCity.LinkType <em>Link Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Link Type</em>'.
   * @see uibk.ac.at.smartcity.smartCity.LinkType
   * @generated
   */
  EEnum getLinkType();

  /**
   * Returns the meta object for enum '{@link uibk.ac.at.smartcity.smartCity.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Data Type</em>'.
   * @see uibk.ac.at.smartcity.smartCity.DataType
   * @generated
   */
  EEnum getDataType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SmartCityFactory getSmartCityFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.ModelImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__NODES = eINSTANCE.getModel_Nodes();

    /**
     * The meta object literal for the '<em><b>Interoperable Layer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INTEROPERABLE_LAYER = eINSTANCE.getModel_InteroperableLayer();

    /**
     * The meta object literal for the '<em><b>Global Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GLOBAL_LINKS = eINSTANCE.getModel_GlobalLinks();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.LayerImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER__PRIORITY = eINSTANCE.getLayer_Priority();

    /**
     * The meta object literal for the '<em><b>Delay</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER__DELAY = eINSTANCE.getLayer_Delay();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.NodeImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__SENSORS = eINSTANCE.getNode_Sensors();

    /**
     * The meta object literal for the '<em><b>Controller</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__CONTROLLER = eINSTANCE.getNode_Controller();

    /**
     * The meta object literal for the '<em><b>Links</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__LINKS = eINSTANCE.getNode_Links();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.SensorImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__TYPE = eINSTANCE.getSensor_Type();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__PRIORITY = eINSTANCE.getSensor_Priority();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.CommunicationLinkImpl <em>Communication Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.CommunicationLinkImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getCommunicationLink()
     * @generated
     */
    EClass COMMUNICATION_LINK = eINSTANCE.getCommunicationLink();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMUNICATION_LINK__TYPE = eINSTANCE.getCommunicationLink_Type();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMUNICATION_LINK__ORIGIN = eINSTANCE.getCommunicationLink_Origin();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMUNICATION_LINK__DESTINATION = eINSTANCE.getCommunicationLink_Destination();

    /**
     * The meta object literal for the '<em><b>Delay</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMUNICATION_LINK__DELAY = eINSTANCE.getCommunicationLink_Delay();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMUNICATION_LINK__DATATYPE = eINSTANCE.getCommunicationLink_Datatype();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.ControllerImpl <em>Controller</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.ControllerImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getController()
     * @generated
     */
    EClass CONTROLLER = eINSTANCE.getController();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.LinkableImpl <em>Linkable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.LinkableImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getLinkable()
     * @generated
     */
    EClass LINKABLE = eINSTANCE.getLinkable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINKABLE__NAME = eINSTANCE.getLinkable_Name();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.impl.DelayRangeImpl <em>Delay Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.impl.DelayRangeImpl
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getDelayRange()
     * @generated
     */
    EClass DELAY_RANGE = eINSTANCE.getDelayRange();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELAY_RANGE__MIN = eINSTANCE.getDelayRange_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DELAY_RANGE__MAX = eINSTANCE.getDelayRange_Max();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.SensorType <em>Sensor Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.SensorType
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getSensorType()
     * @generated
     */
    EEnum SENSOR_TYPE = eINSTANCE.getSensorType();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.LinkType <em>Link Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.LinkType
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getLinkType()
     * @generated
     */
    EEnum LINK_TYPE = eINSTANCE.getLinkType();

    /**
     * The meta object literal for the '{@link uibk.ac.at.smartcity.smartCity.DataType <em>Data Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uibk.ac.at.smartcity.smartCity.DataType
     * @see uibk.ac.at.smartcity.smartCity.impl.SmartCityPackageImpl#getDataType()
     * @generated
     */
    EEnum DATA_TYPE = eINSTANCE.getDataType();

  }

} //SmartCityPackage
