grammar uibk.ac.at.smartcity.SmartCity with org.eclipse.xtext.common.Terminals

generate smartCity "http://www.ac.uibk/at/smartcity/SmartCity"

Model:
	nodes+=Node*
	dataGateway=DataGateway
	globalLinks+=CommunicationLink* // by default all the nodes will already be connected to the dataGateway
	simulationProperties=SimulationProperties
;

SimulationProperties:
	'simulationProperties' '{'
		'terminationTime' terminationTime=INT
		('generatorFile' generatorFile=STRING)?
	'}'
;

DataGateway:
	'dataGateway' name=ID
	'{'
		'priority' priority=INT
		'delay' delay=DelayRange
	'}'
;
	
Node:
	'node' name=ID
	'{'
		sensors+=Sensor*
		modules+=Module*
		controller=Controller
		links+=CommunicationLink*
		'postFrequency' frequency=Frequency
		'priority' priority=INT
	'}'
;

Sensor:
	'sensor' name=ID
	'{'
		'type' type=SensorType
		'priority' priority=INT
		cyclicActions+=CyclicAction*
		triggeredActions+=TriggeredAction*
	'}'
;

CommunicationLink:
	'link' type=LinkType 'from' origin=[Linkable] '->' destination=[Linkable] '{'
		'delay' delay=DelayRange
		'datatype' datatype=SensorType
	'}'
;

Controller:
	'controller' name=ID
	'{'
		'type' type=ControllerType
		'priority' priority=INT
		cyclicActions+=CyclicAction*
		triggeredActions+=TriggeredAction*
	'}'
;

Module:
	'module' name=ID
	'{'
		'priority' priority=INT
		cyclicActions+=CyclicAction*
		triggeredActions+=TriggeredAction*		
	'}'
;

Frequency:
	value=INT unit=FrequencyUnit
;

Linkable:
	Controller | Sensor | DataGateway | Node | Module
;

DelayRange:
	'[' min=INT '..' max=INT ']'
;

CyclicAction:
	'cyclicAction' name=ID
	'frequency' frequency=Frequency
;

TriggeredAction:
	'TriggeredAction' name=ID
;
	
enum SensorType:
	TEMPERATURE | PH | TURBIDITY | TDS | CURRENT | PULSE | ULTRASONIC | CAMERA | GSM
;

enum ControllerType:
	ESP32 | RASPBERRY_PI | OTHER
;

enum LinkType:
	UART | ADC | SPI | CSI | HTTPS
;

enum DataType:
	BOOL | FLOAT | EPOCH | STRING | DOUBLE
;

enum FrequencyUnit:
	HERTZ | SECONDS | MINUTES | HOURS |DAYS | INF
;