/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uibk.ac.at.smartcity.ui.internal.SmartcityActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmartCityExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SmartcityActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SmartcityActivator activator = SmartcityActivator.getInstance();
		return activator != null ? activator.getInjector(SmartcityActivator.UIBK_AC_AT_SMARTCITY_SMARTCITY) : null;
	}

}
