/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.generator

import java.util.HashMap
import java.util.HashSet
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import uibk.ac.at.smartcity.smartCity.CommunicationLink
import uibk.ac.at.smartcity.smartCity.Node
import uibk.ac.at.smartcity.smartCity.Sensor
import java.util.ArrayList
import uibk.ac.at.smartcity.smartCity.InteroperableLayer
import uibk.ac.at.smartcity.smartCity.SensorType
import uibk.ac.at.smartcity.smartCity.FrequencyUnit
import uibk.ac.at.smartcity.smartCity.ControllerType

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class SmartCityGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
//		fsa.generateFile('greetings.txt', 'People to greet: ' + 
//			resource.allContents
//				.filter(Greeting)
//				.map[name]
//				.join(', '))



		// first create nodes, in there the sensors
		for (node: resource.allContents.toIterable.filter(Node)){
			fsa.generateFile("nodes/" + node.name + ".py", node.compile)
			for(sensor: node.sensors){
				fsa.generateFile("sensors/" + sensor.name + ".py", sensor.compile)
			}
		}
		
		
		// generate communication models
		// generateCommunications(fsa)
		
		// generate blueprint for the interface
		generateInterface(fsa)
		
		// generate hardcoded sink
		generateSink(fsa)
		
		// create the model
		val sensors = resource.allContents.toIterable.filter(Sensor)
		val links = resource.allContents.toIterable.filter(CommunicationLink)
		val nodes = resource.allContents.toIterable.filter(Node)
		val interoperableLayer = resource.allContents.toIterable.filter(InteroperableLayer).get(0)
		
		fsa.generateFile("model.py", generateModel(sensors, links, nodes, interoperableLayer))
				
		// main:
		fsa.generateFile("experiment.py", generateMain())
	}
	
	def double frequencyToSeconds(int value, FrequencyUnit unit){
		switch (unit) {
			case DAYS: {
				return value * 24 * 60 * 60
			}
			case HOURS: {
				return value * 60 * 60
			}
			case SECONDS: {
				return value
			}
			case HERTZ: {
				return 1/value
			}
			case INF: {
				return -1
			}
			default: {
				return value
			}
		}
	}
	
	def compile(Sensor sensor){
		'''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		import random
		import time
		
		class «sensor.name.toFirstUpper»(AtomicDEVS):
			«IF sensor.type == SensorType.CAMERA»
			def __init__(self):
				super().__init__("«sensor.name»")
				self.in_port = self.addInPort("in_port")
				self.outport = self.addOutPort("outport")
				self.state = {
					"number": 0,
					"image_data": None,
					"number_detected": None,
					"processing_time": 0,
					"status": "capturing"  # Start in capturing state
				}
				self.priority = «sensor.priority»
			def generate_random_number(self):
				return random.randint(0, 100)
			
			def capture_image(self):
				# Simulate capturing an image
				self.state["image_data"] = f"image_data_{time.time()}"
				print(f"[{self.name}] Captured image: {self.state['image_data']}")

			def process_image(self):
				# Simulate processing the image to detect a number
				self.state["number_detected"] = self.generate_random_number()
				print(f"[{self.name}] Detected number: {self.state['number_detected']}")
			«ELSE»
			def __init__(self):
				super().__init__("«sensor.name»")
				self.inport = self.addInPort("in_port")
				self.outport = self.addOutPort("outport")
				self.state = {"«sensor.type»": 0}
				self.priority = «sensor.priority»
  		 	«ENDIF»

			def intTransition(self):
				«IF (sensor.type == SensorType.PH)»
				self.state["«sensor.type»"] = random.uniform(0, 14)
				return self.state
				«ELSEIF (sensor.type == SensorType.CURRENT)»
				self.state["«sensor.type»"] = random.uniform(0, 100)
				return self.state
				«ELSEIF (sensor.type == SensorType.PULSE)»
				self.state["«sensor.type»"] = random.uniform(0, 1)
				return self.state
				«ELSEIF (sensor.type == SensorType.TDS)»
				self.state["«sensor.type»"] = random.uniform(0, 1000)
				return self.state
				«ELSEIF (sensor.type == SensorType.TEMPERATURE)»
				self.state["«sensor.type»"] = random.uniform(0, 100)
				return self.state
				«ELSEIF (sensor.type == SensorType.TURBIDITY)»
				self.state["«sensor.type»"] = random.uniform(0, 100)
				return self.state
				«ELSEIF (sensor.type == SensorType.ULTRASONIC)»
				self.state["«sensor.type»"] = random.uniform(0.5, 4.0)
				return self.state
				«ELSEIF (sensor.type == SensorType.CAMERA)»
				if self.state["status"] == "capturing":
					self.capture_image()
					self.state["status"] = "processing"
				elif self.state["status"] == "processing":
					self.process_image()
					self.state["status"] = "capturing"  # Loop back to capturing for continuous processing
				return self.state
				«ELSE»
				print("Internal Transition not defined for this sensor type")
				return None
				«ENDIF»

			def extTransition(self, inputs):
				«IF (sensor.type == SensorType.CAMERA)»
				self.state["status"] = "capturing"
				return self.state
				«ELSE»
				return self.state
				«ENDIF»

			def outputFnc(self):
				«IF (sensor.type == SensorType.CAMERA)»
				if self.state["status"] == "processing" and self.state["number_detected"] is not None:
					print(f"[{self.name}] Outputting detected number: {self.state['number_detected']}")
					return {self.outport: self.state["number_detected"]}
				return {}
				«ELSE»
				return {self.outport: self.state['«sensor.type»']}
				«ENDIF»

			def timeAdvance(self):
				«IF (sensor.type == SensorType.CAMERA)»
				if self.state["status"] == "idle":
					return INFINITY
				elif self.state["status"] == "capturing":
					return 1.0  # Time to capture an image
				elif self.state["status"] == "processing":
					return 2.0  # Time to process the image
				return INFINITY
				«ELSEIF (sensor.type == SensorType.CURRENT || sensor.type == SensorType.PULSE || sensor.type == SensorType.ULTRASONIC)»
				return 1.0
				«ELSE»
				return 5.0
				«ENDIF»
				
			def __lt__(self, other):
				return self.priority < other.priority
		'''
	}
	
	def compile(Node node){
		val nodeLinks = new ArrayList
		val distinctLinkTypes = new HashSet()
		for (link:node.links){
			nodeLinks.add(link)
			distinctLinkTypes.add(link.type)
		}
		val postFrequency = frequencyToSeconds(node.freqValue, node.freqUnit)
		val boolean knownController = node.controller.type != ControllerType.OTHER
		
		'''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		import time, random
		class «node.name.toFirstUpper»State:
			def __init__(self):
				self.data_aggregated = {}
				
				if random.random() < 0.8:
					self.next_internal_time = «postFrequency»
				else:
					self.next_internal_time = «postFrequency» + random.uniform(«postFrequency» * (-0.8), «postFrequency» * 0.8)
		
		
		class «node.name.toFirstUpper»(AtomicDEVS):
			def __init__(self, name, pinout):
				super().__init__(name)
				self.state = «node.name.toFirstUpper»State()
				self.timeLast = 0.0  # Initialize timeLast
				self.pins = pinout
				«IF knownController»
				«FOR type: distinctLinkTypes»
				self.«type.toString.toLowerCase»_inport = self.addInPort("«type.toString.toLowerCase»_in")
		        «ENDFOR»
				«ELSE»
				«FOR type: distinctLinkTypes»
				self.«type.toString.toLowerCase»_inport = self.addInPort("«type.toString.toLowerCase»_in")
		        «ENDFOR»
		        «ENDIF»
				self.outport = self.addOutPort("out")
				self.priority = «node.priority»  # Priority for nodes
		
			def timeAdvance(self):
				# Calculate the remaining time until the next send event
				print(f"[{self.name}] timeAdvance called. Next internal time: {self.state.next_internal_time}, timeLast: {self.timeLast}")
				return self.state.next_internal_time - self.timeLast if self.state.data_aggregated else INFINITY
				
			def extTransition(self, inputs):
				# Update the state based on inputs from the connections
				print(f"[{self.name}] extTransition called with inputs: {inputs}")
				«FOR link: node.links»
				«IF link.destination === node.controller»
				# self.«link.type.toString.toLowerCase»_inport = self.addInPort("«link.type.toString.toLowerCase»_in")
				if self.«link.type.toString.toLowerCase»_inport in inputs:
					self.state.data_aggregated["«link.type»"] = inputs[self.«link.type.toString.toLowerCase»_inport]
				«ENDIF»
				«ENDFOR»
				self.timeLast = self.state.next_internal_time  # Update timeLast
				return self.state
				
			def intTransition(self):
				# Schedule the next send time
				print(f"[{self.name}] intTransition called.")
				self.timeLast = self.state.next_internal_time  # Update timeLast
				self.state.next_internal_time += 1.0
				return self.state

		# TODO: Discuss how this format should be handeled, maybe we need Node Type in the metamodel
			def outputFnc(self):
				# Only send data if there is aggregated data
				if self.state.data_aggregated:
					timestamp = str(int(time.time()))
					data_to_send = {
					    "m2m:cin": {
					        "lbl": ['«node.name»'],
					        "con": [
					        	timestamp,
					        	*self.state.data_aggregated
					        ]
					    }
					}
					print(f"[{self.name}] Sending aggregated data: {data_to_send}")
					# Clear the aggregated data after sending
					self.state.data_aggregated = {}
					return {self.outport: data_to_send}
				else:
					print(f"[{self.name}] No data to send.")
					return {}
		
			def __lt__(self, other):
				# Define comparison logic based on priority attribute
				return self.priority < other.priority
		'''
	}
	
	def compile(Iterable<CommunicationLink> links){
		var linksList = new ArrayList()
		var distinct = new HashSet()
		for (link: links){
			linksList.add(link) // used to persist the iterator
			distinct.add(link.type)
		}
		
		// for each distinct create array of datatypes
		var linkDataMap = new HashMap()
		for (type:distinct){
			linkDataMap.put(type, "[")
			for(link:linksList){
				if(link.type === type){
					linkDataMap.put(type, linkDataMap.get(type) + "'" + link.datatype.toString + "'" + ", ")				
				}
			}
			val len = linkDataMap.get(type).length
			if (len > 2){
				linkDataMap.put(type, linkDataMap.get(type).substring(0, len - 2))
			}
			linkDataMap.put(type, linkDataMap.get(type) + "]")
		}
		
		
		'''
		«FOR linkType:linkDataMap.keySet»
		from communications.«linkType.toString.toLowerCase»_comm import «linkType.toString.toUpperCase»
		«linkType.toString» = self.addSubModel(«linkType.toString.toUpperCase»("«linkType.toString»", «linkDataMap.get(linkType)»))
		«ENDFOR»
		# Connect sensors to communication models
		«FOR link:linksList»
		self.connectPorts(«link.origin.name».outport, «link.type.toString».inports["«link.datatype.toString»"])
		«ENDFOR»
		'''
	}
	
	def generateMain(){
		'''
		from pypdevs.simulator import Simulator
		from model import Model
		import logging
		logging.basicConfig(level=logging.DEBUG)
		if __name__ == '__main__':
			logging.debug("Starting the model")
			model = Model()
			logging.debug("Model Loaded")
			sim = Simulator(model)
			logging.debug("Simulator Loaded")
			sim.setClassicDEVS()
			logging.debug("Classic DEVS set")
			
			sim.setVerbose()
			logging.debug("Verbose mode set")
			
			# sim.setTerminationTime(86400)  # 24 hours
			sim.setTerminationTime(300) # 5 minutes
			logging.debug("Termination time set")
			
			logging.debug("Starting simulation")
			sim.simulate()
			logging.debug("Simulation finished")		
		'''
	}
	
	def generateModel(Iterable<Sensor> sensors, Iterable<CommunicationLink> links, Iterable<Node> nodes, InteroperableLayer interoperableLayer){
		var commLinks = new ArrayList<CommunicationLink>
		for (link:links){
			commLinks.add(link)
		}
		
		val nodesList = new ArrayList<Node>
		for (node: nodes){
			nodesList.add(node)
		}
		
		val sensorList = new ArrayList<Sensor>
		for (sensor: sensors){
			sensorList.add(sensor)
		}
		
		'''
		from pypdevs.DEVS import CoupledDEVS
		from sink import Sink
		from layers.m2m_interface import M2MInterface
		
		esp32_pins = {
		    # ESP32 NodeMCU Pin Configuration
		    "ADC": [32, 33, 34, 35, 36, 39],
		    "DIGITAL_IO": [0, 2, 4, 12, 13, 14, 15],
		    "PWM": [16, 17, 18, 19, 21, 23],
		    "I2C": [22, 27],
		    "SPI": [5, 18, 19, 23],
		    "UART": [1, 3, 9, 10, 16, 17],
		    "DAC": [25, 26],
		    "TOUCH": [0, 2, 4, 12, 13, 14, 27],
		    "RTC": [32, 33, 34, 35, 36, 39],
		    "POWER": {"3V3": "External", "GND": "External"}
		}
		
		raspberry_pi_pins = {
		    # Raspberry Pi GPIO Pin Configuration (Raspberry Pi 4 Model B)
		    "GPIO": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
		    "I2C": [2, 3],  # SDA, SCL
		    "SPI": [10, 11, 12, 13, 14, 15],  # MOSI, MISO, SCLK, CE0, CE1
		    "UART": [14, 15],  # TX, RX
		    "PWM": [18],  # PWM pin
		    "ADC": None,  # Raspberry Pi does not have built-in ADC, requires external ADC like MCP3008
		    "DIGITAL_IO": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],  # GPIO pins
		    "DAC": None,  # Raspberry Pi does not have built-in DAC, requires external DAC like MCP4725
		    "TOUCH": None,  # Raspberry Pi does not have built-in touch pins
		    "RTC": None,  # External RTC module like DS3231 is needed
		    "POWER": {"3V3": "External", "GND": "External"},
		    "CSI": "Camera Serial Interface (CSI) Port",  # Special port for camera connection
		}
		
		
		class Model(CoupledDEVS):
			def __init__(self):
				super().__init__("SmartCityModel")
				# Sensors
				«FOR sensor: sensorList»
				from sensors.«sensor.name» import «sensor.name.toFirstUpper»
				«sensor.name» = self.addSubModel(«sensor.name.toFirstUpper»())
				«ENDFOR»
				
				# Nodes
				«FOR node:nodesList»
				from nodes.«node.name» import «node.name.toFirstUpper»
				«IF node.controller.type == ControllerType.OTHER»
				«node.name» = self.addSubModel(«node.name.toFirstUpper»("«node.name.toFirstUpper»"), None)
				«ELSE»
				«node.name» = self.addSubModel(«node.name.toFirstUpper»("«node.name.toFirstUpper»", «node.controller.type.toString.toLowerCase»_pins))
				«ENDIF»
				«ENDFOR»
				# Interface
				interfaceLayer = self.addSubModel(M2MInterface("«interoperableLayer.name»", priority=«interoperableLayer.priority»))
				sink = self.addSubModel(Sink("Sink"))

				«FOR node:nodesList»
				«FOR link:node.links»
				«IF link.destination === node.controller»
				self.connectPorts(«link.origin.name».outport, «node.name».«link.type.toString.toLowerCase»_inport)
				«ENDIF»
				«ENDFOR»

				self.connectPorts(«node.name».outport, interfaceLayer.inport)

				«ENDFOR»
				self.connectPorts(interfaceLayer.outport, sink.inport)
		'''
	}
	
	def generateInterface(IFileSystemAccess2 fsa){
		val m2minterface = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class InterfaceState:
			def __init__(self):
				self.processing_time = 0.0
				self.data_to_send = None
				
		class M2MInterface(AtomicDEVS):
			def __init__(self, name, simulated_delay=1.0, priority=1):
				super().__init__(name)
				self.simulated_delay = float(simulated_delay)  # Ensure simulated_delay is a float
				self.state = InterfaceState()
				self.timeLast = 0.0
				self.inport = self.addInPort("in")
				self.outport = self.addOutPort("out")
				self.priority = priority  # Example priority attribute
				
			def timeAdvance(self):
				if self.state.data_to_send is None:
					return INFINITY
				return self.state.processing_time - self.timeLast
			    
			def extTransition(self, inputs):
				self.state.data_to_send = inputs[self.inport]
				self.state.processing_time = self.timeLast + self.simulated_delay
				return self.state
				
			def outputFnc(self):
				sensor_data = self.state.data_to_send
				transformed_data = {
			        "m2m:sgn": {
			            "m2m:nev": {
			                "m2m:rep": {
			                    "m2m:cin": {
			                        "con": sensor_data["m2m:cin"]["con"],
			                        "ri": "cin7124901579521707503",
			                        "pi": "cnt8702778900039637980",
			                        "rn": "cin_UKmyMwKBXt",
			                        "ct": "20231207T061300,532674",
			                        "lt": "20231207T061300,532674",
			                        "ty": 4,
			                        "cs": len(sensor_data["m2m:cin"]["con"]),
			                        "st": 0,
			                        "cnf": "text/plain:0",
			                        "con": sensor_data["m2m:cin"]["con"]
			                    }
			                },
			                "m2m:rss": 1
			            },
			            "m2m:sud": 'false',
			            "m2m:sur": "/in-cse/sub-632211058"
			        }
			    }
				self.state.data_to_send = None
				print(f"OneM2M Interface simulated sending: {transformed_data}")
				return {self.outport: transformed_data}

			def intTransition(self):
				self.timeLast = self.state.processing_time
				self.state.processing_time = INFINITY
				return self.state
			    
			def __lt__(self, other):
				# Define comparison logic based on priority attribute
				return self.priority < other.priority
		'''
		
		fsa.generateFile("layers/m2m_interface.py", m2minterface)
	}
	
	def generateSink(IFileSystemAccess2 fsa){
		val sink = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class Sink(AtomicDEVS):
		    def __init__(self, name="Sink"):
		        super().__init__(name)
		        self.inport = self.addInPort("in")
		        
		    def extTransition(self, inputs):
		        print(f"[{self.name}] Received data: {inputs[self.inport]}")
		        return self.state
		        
		    def timeAdvance(self):
		        return INFINITY
		        
		    def outputFnc(self):
		        return {}
		'''
		fsa.generateFile("sink.py", sink)
	}
	
	def generateCommunications(IFileSystemAccess2 fsa){
		val adc_comm = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class ADCState:
		    def __init__(self):
		        self.data = {}
		        self.next_internal_time = INFINITY
		        
		class ADC(AtomicDEVS):
		    def __init__(self, name, data_types=None):
		        super().__init__(name)
		        self.state = ADCState()
		        self.data_types = data_types or []
		        self.inports = {data_type: self.addInPort(f"in_{data_type}") for data_type in self.data_types}
		        self.outport = self.addOutPort("out")
		        self.priority = 2  # Priority for communication models
		        
		    def timeAdvance(self):
		        return self.state.next_internal_time
		        
		    def extTransition(self, inputs):
		        for data_type, port in self.inports.items():
		            if port in inputs:
		                self.state.data[data_type] = inputs[port]
		                print(f"[{self.name}] Received {data_type} value: {inputs[port]}")
		        self.state.next_internal_time = 0.0  # Schedule an immediate internal transition
		        return self.state
		        
		    def outputFnc(self):
		        # Forward the received data to the WaterQualityNode
		        data_to_send = {"sensor_id": self.name, **self.state.data}
		        print(f"[{self.name}] Forwarding data: {data_to_send}")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return {self.outport: data_to_send}
		        
		    def intTransition(self):
		        print(f"[{self.name}] intTransition called.")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return self.state
		        
		    def __lt__(self, other):
		        return self.priority < other.priority
		'''
		
		val csi_comm = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class CSIState:
		    def __init__(self):
		        self.data = {}
		        self.next_internal_time = INFINITY
		        
		class CSI(AtomicDEVS):
		    def __init__(self, name, data_types=None):
		        super().__init__(name)
		        self.state = CSIState()
		        self.data_types = data_types or []
		        self.inports = {data_type: self.addInPort(f"in_{data_type}") for data_type in self.data_types}
		        self.outport = self.addOutPort("out")
		        self.priority = 2  # Priority for communication models
		        
		    def timeAdvance(self):
		        return self.state.next_internal_time
		        
		    def extTransition(self, inputs):
		        for data_type, port in self.inports.items():
		            if port in inputs:
		                self.state.data[data_type] = inputs[port]
		                print(f"[{self.name}] Received {data_type} value: {inputs[port]}")
		        self.state.next_internal_time = 0.0  # Schedule an immediate internal transition
		        return self.state
		        
		    def outputFnc(self):
		        # Forward the received data to the WaterQualityNode
		        data_to_send = {"sensor_id": self.name, **self.state.data}
		        print(f"[{self.name}] Forwarding data: {data_to_send}")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return {self.outport: data_to_send}
		        
		    def intTransition(self):
		        print(f"[{self.name}] intTransition called.")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return self.state
		        
		    def __lt__(self, other):
		        return self.priority < other.priority
		'''
		
		
		val gpio_comm = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class GPIOState:
		    def __init__(self):
		        self.data = {}
		        self.next_internal_time = INFINITY
		        
		class GPIO(AtomicDEVS):
		    def __init__(self, name, data_types=None):
		        super().__init__(name)
		        self.state = GPIOState()
		        self.data_types = data_types or []
		        self.inports = {data_type: self.addInPort(f"in_{data_type}") for data_type in self.data_types}
		        self.outport = self.addOutPort("out")
		        self.priority = 2  # Priority for communication models
		        
		    def timeAdvance(self):
		        return self.state.next_internal_time
		        
		    def extTransition(self, inputs):
		        for data_type, port in self.inports.items():
		            if port in inputs:
		                self.state.data[data_type] = inputs[port]
		                print(f"[{self.name}] Received {data_type} value: {inputs[port]}")
		        self.state.next_internal_time = 0.0  # Schedule an immediate internal transition
		        return self.state
		        
		    def outputFnc(self):
		        # Forward the received data to the WaterQualityNode
		        data_to_send = {"sensor_id": self.name, **self.state.data}
		        print(f"[{self.name}] Forwarding data: {data_to_send}")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return {self.outport: data_to_send}
		        
		    def intTransition(self):
		        print(f"[{self.name}] intTransition called.")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return self.state
		        
		    def __lt__(self, other):
		        return self.priority < other.priority
		'''
		
		val http_comm = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class HTTPState:
		    def __init__(self):
		        self.data = {}
		        self.next_internal_time = INFINITY
		        
		class HTTP(AtomicDEVS):
		    def __init__(self, name, data_types=None):
		        super().__init__(name)
		        self.state = HTTPState()
		        self.data_types = data_types or []
		        self.inports = {data_type: self.addInPort(f"in_{data_type}") for data_type in self.data_types}
		        self.outport = self.addOutPort("out")
		        self.priority = 2  # Priority for communication models
		        
		    def timeAdvance(self):
		        return self.state.next_internal_time
		        
		    def extTransition(self, inputs):
		        for data_type, port in self.inports.items():
		            if port in inputs:
		                self.state.data[data_type] = inputs[port]
		                print(f"[{self.name}] Received {data_type} value: {inputs[port]}")
		        self.state.next_internal_time = 0.0  # Schedule an immediate internal transition
		        return self.state
		        
		    def outputFnc(self):
		        # Forward the received data to the WaterQualityNode
		        data_to_send = {"sensor_id": self.name, **self.state.data}
		        print(f"[{self.name}] Forwarding data: {data_to_send}")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return {self.outport: data_to_send}
		        
		    def intTransition(self):
		        print(f"[{self.name}] intTransition called.")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return self.state
		        
		    def __lt__(self, other):
		        return self.priority < other.priority
		'''
		
		val spi_comm = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class SPIState:
		    def __init__(self):
		        self.data={}
		        self.next_internal_time = INFINITY
		        
		class SPI(AtomicDEVS):
		    def __init__(self, name, data_types=None):
		        super().__init__(name)
		        self.state = SPIState()
		        self.data_types = data_types or []
		        self.inports = {data_type: self.addInPort(f"in_{data_type}") for data_type in self.data_types}
		        self.outport = self.addOutPort("out")
		        self.priority = 2
		        
		    def timeAdvance(self):
		        return self.state.next_internal_time
		        
		    def extTransition(self, inputs):
		        for data_type, port in self.inports.items():
		            if port in inputs:
		                self.state.data[data_type] = inputs[port]
		                print(f"[{self.name}] Received {data_type} value: {inputs[port]}")
		        self.state.next_internal_time = 0.0  # Schedule an immediate internal transition
		        return self.state
		        
		    def outputFnc(self):
		        # Forward the received data to the WaterQualityNode
		        data_to_send = {"sensor_id": self.name, **self.state.data}
		        print(f"[{self.name}] Forwarding data: {data_to_send}")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return {self.outport: data_to_send}
		        
		    def intTransition(self):
		        print(f"[{self.name}] intTransition called.")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return self.state
		        
		    def __lt__(self, other):
		        return self.priority < other.priority
		'''
		
		val uart_comm = '''
		from pypdevs.DEVS import AtomicDEVS
		from pypdevs.infinity import INFINITY
		class UARTState:
		    def __init__(self):
		        self.data = {}
		        self.next_internal_time = INFINITY
		        
		class UART(AtomicDEVS):
		    def __init__(self, name, data_types=None):
		        super().__init__(name)
		        self.state = UARTState()
		        self.data_types = data_types or []
		        self.inports = {data_type: self.addInPort(f"in_{data_type}") for data_type in self.data_types}
		        self.outport = self.addOutPort("out")
		        self.priority = 2  # Priority for communication models
		        
		    def timeAdvance(self):
		        return self.state.next_internal_time
		        
		    def extTransition(self, inputs):
		        for data_type, port in self.inports.items():
		            if port in inputs:
		                self.state.data[data_type] = inputs[port]
		                print(f"[{self.name}] Received {data_type} value: {inputs[port]}")
		        self.state.next_internal_time = 0.0  # Schedule an immediate internal transition
		        return self.state
		        
		    def outputFnc(self):
		        # Forward the received data to the WaterQualityNode
		        data_to_send = {"sensor_id": self.name, **self.state.data}
		        print(f"[{self.name}] Forwarding data: {data_to_send}")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return {self.outport: data_to_send}
		        
		    def intTransition(self):
		        print(f"[{self.name}] intTransition called.")
		        self.state.next_internal_time = INFINITY  # Reset the internal time
		        return self.state
		        
		    def __lt__(self, other):
		        return self.priority < other.priority
		'''
		
		fsa.generateFile("communications/adc_comm.py", adc_comm)		
		fsa.generateFile("communications/csi_comm.py", csi_comm)		
		fsa.generateFile("communications/gpio_comm.py", gpio_comm)		
		fsa.generateFile("communications/http_comm.py", http_comm)		
		fsa.generateFile("communications/spi_comm.py", spi_comm)		
		fsa.generateFile("communications/uart_comm.py", uart_comm)		
	}
}
