/*
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmartCityUiModule extends AbstractSmartCityUiModule {

	public SmartCityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
