/**
 * generated by Xtext 2.36.0
 */
package org.smartcitymodel.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.smartcitymodel.dsl.Port#getId <em>Id</em>}</li>
 *   <li>{@link org.smartcitymodel.dsl.Port#getDirection <em>Direction</em>}</li>
 *   <li>{@link org.smartcitymodel.dsl.Port#getType <em>Type</em>}</li>
 *   <li>{@link org.smartcitymodel.dsl.Port#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see org.smartcitymodel.dsl.DslPackage#getPort()
 * @model
 * @generated
 */
public interface Port extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(int)
   * @see org.smartcitymodel.dsl.DslPackage#getPort_Id()
   * @model
   * @generated
   */
  int getId();

  /**
   * Sets the value of the '{@link org.smartcitymodel.dsl.Port#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(int value);

  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link org.smartcitymodel.dsl.DIRECTION}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see org.smartcitymodel.dsl.DIRECTION
   * @see #setDirection(DIRECTION)
   * @see org.smartcitymodel.dsl.DslPackage#getPort_Direction()
   * @model
   * @generated
   */
  DIRECTION getDirection();

  /**
   * Sets the value of the '{@link org.smartcitymodel.dsl.Port#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see org.smartcitymodel.dsl.DIRECTION
   * @see #getDirection()
   * @generated
   */
  void setDirection(DIRECTION value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.smartcitymodel.dsl.TYPE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.smartcitymodel.dsl.TYPE
   * @see #setType(TYPE)
   * @see org.smartcitymodel.dsl.DslPackage#getPort_Type()
   * @model
   * @generated
   */
  TYPE getType();

  /**
   * Sets the value of the '{@link org.smartcitymodel.dsl.Port#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.smartcitymodel.dsl.TYPE
   * @see #getType()
   * @generated
   */
  void setType(TYPE value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * The literals are from the enumeration {@link org.smartcitymodel.dsl.UNIT}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see org.smartcitymodel.dsl.UNIT
   * @see #setUnit(UNIT)
   * @see org.smartcitymodel.dsl.DslPackage#getPort_Unit()
   * @model
   * @generated
   */
  UNIT getUnit();

  /**
   * Sets the value of the '{@link org.smartcitymodel.dsl.Port#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see org.smartcitymodel.dsl.UNIT
   * @see #getUnit()
   * @generated
   */
  void setUnit(UNIT value);

} // Port
