/**
 * generated by Xtext 2.36.0
 */
package org.smartcitymodel.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.smartcitymodel.dsl.DslPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
