/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.validation;

import java.io.File;
import java.util.Objects;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import uibk.ac.at.smartcity.smartCity.CommunicationLink;
import uibk.ac.at.smartcity.smartCity.Controller;
import uibk.ac.at.smartcity.smartCity.ControllerType;
import uibk.ac.at.smartcity.smartCity.CyclicAction;
import uibk.ac.at.smartcity.smartCity.DataGateway;
import uibk.ac.at.smartcity.smartCity.DelayRange;
import uibk.ac.at.smartcity.smartCity.Frequency;
import uibk.ac.at.smartcity.smartCity.Linkable;
import uibk.ac.at.smartcity.smartCity.Model;
import uibk.ac.at.smartcity.smartCity.Node;
import uibk.ac.at.smartcity.smartCity.Sensor;
import uibk.ac.at.smartcity.smartCity.SensorType;
import uibk.ac.at.smartcity.smartCity.SimulationProperties;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;
import uibk.ac.at.smartcity.smartCity.TriggeredAction;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmartCityValidator extends AbstractSmartCityValidator {
  protected static final String ISSUE_CODE_PREFIX = "uibk.ac.at.smartcity.";

  public static final String INVALID_ENTITY_NAME = "InvalidEntityName";

  public static final String INVALID_ATTRIBUTE_NAME = "InvalidAttributeName";

  @Check
  public void checkNodeStartsWithCapital(final Node node) {
    boolean _isLowerCase = Character.isLowerCase(node.getName().charAt(0));
    if (_isLowerCase) {
      this.warning(
        "Node name should start with a capital", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ENTITY_NAME, 
        node.getName());
    }
  }

  @Check
  public void checkDataGatewayStartsWithCapital(final DataGateway dataGateway) {
    boolean _isLowerCase = Character.isLowerCase(dataGateway.getName().charAt(0));
    if (_isLowerCase) {
      this.warning(
        "DataGateway name should start with a capital", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ENTITY_NAME, 
        dataGateway.getName());
    }
  }

  @Check
  public void checkSensorNamesAreLowerCase(final Sensor sensor) {
    boolean _isUpperCase = Character.isUpperCase(sensor.getName().charAt(0));
    if (_isUpperCase) {
      this.warning(
        "Sensor name should start with a lower case letter", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ATTRIBUTE_NAME, 
        sensor.getName());
    }
  }

  @Check
  public void checkModuleNamesAreLowerCase(final Module module) {
    boolean _isUpperCase = Character.isUpperCase(module.getName().charAt(0));
    if (_isUpperCase) {
      this.warning(
        "Module name should start with a lower case letter", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ATTRIBUTE_NAME, 
        module.getName());
    }
  }

  @Check
  public void checkControllerNamesAreLowerCase(final Controller controller) {
    boolean _isUpperCase = Character.isUpperCase(controller.getName().charAt(0));
    if (_isUpperCase) {
      this.warning(
        "Controller name should start with a lower case letter", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ATTRIBUTE_NAME, 
        controller.getName());
    }
  }

  @Check
  public void checkSimulationPropertiesNonNegativeTerminationTime(final SimulationProperties props) {
    int _terminationTime = props.getTerminationTime();
    boolean _lessEqualsThan = (_terminationTime <= 0);
    if (_lessEqualsThan) {
      this.error(
        "Termination Time for the simulation must be larger than 0", 
        SmartCityPackage.Literals.SIMULATION_PROPERTIES__TERMINATION_TIME);
    }
  }

  @Check
  public void checkSimulationPropertiesFileExists(final SimulationProperties props) {
    boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(props.getGeneratorFile());
    boolean _not = (!_isNullOrEmpty);
    if (_not) {
      String _generatorFile = props.getGeneratorFile();
      File f = new File(_generatorFile);
      if (((!f.exists()) || f.isDirectory())) {
        this.error(
          "Can not find this File, please check the path", 
          SmartCityPackage.Literals.SIMULATION_PROPERTIES__GENERATOR_FILE);
      } else {
        boolean _endsWith = f.getName().endsWith(".csv");
        boolean _not_1 = (!_endsWith);
        if (_not_1) {
          this.error(
            "The Generator File must be of a \'csv\' File", 
            SmartCityPackage.Literals.SIMULATION_PROPERTIES__GENERATOR_FILE);
        }
      }
    }
  }

  @Check
  public void modelContainsAtLeastOneNode(final Model model) {
    int _length = ((Object[])Conversions.unwrapArray(model.getNodes(), Object.class)).length;
    boolean _lessThan = (_length < 1);
    if (_lessThan) {
      this.error(
        "The Model needs to contain at least one Node for the simulation", 
        SmartCityPackage.Literals.MODEL__NODES);
    }
  }

  @Check
  public Object checkNodeBalance(final Node node) {
    Object _switchResult = null;
    ControllerType _type = node.getController().getType();
    if (_type != null) {
      switch (_type) {
        case ESP32:
          int _size = node.getSensors().size();
          boolean _greaterThan = (_size > 8);
          if (_greaterThan) {
            this.warning("ESP32 controller might be overloaded with too many sensors", 
              SmartCityPackage.Literals.LINKABLE__NAME);
          }
          break;
        case RASPBERRY_PI:
          int _size_1 = node.getSensors().size();
          boolean _greaterThan_1 = (_size_1 > 16);
          if (_greaterThan_1) {
            this.warning("Raspberry Pi controller might be overloaded with too many sensors", 
              SmartCityPackage.Literals.LINKABLE__NAME);
          }
          break;
        default:
          _switchResult = null;
          break;
      }
    } else {
      _switchResult = null;
    }
    return _switchResult;
  }

  @Check
  public void checkDelayRangeIsValid(final DelayRange range) {
    int _max = range.getMax();
    int _min = range.getMin();
    boolean _lessThan = (_max < _min);
    if (_lessThan) {
      this.error(
        "Invalid Delay Range: Second value can not be smaller than the first", 
        SmartCityPackage.Literals.DELAY_RANGE__MAX);
    }
  }

  @Check
  public void checkDelayRangeNotNegative(final DelayRange range) {
    int _min = range.getMin();
    boolean _lessThan = (_min < 0);
    if (_lessThan) {
      this.error(
        "Delay minimum cannot be negative", 
        SmartCityPackage.Literals.DELAY_RANGE__MIN);
    }
  }

  @Check
  public void checkDelayRangeTooLarge(final DelayRange range) {
    int _max = range.getMax();
    boolean _greaterThan = (_max > 100000);
    if (_greaterThan) {
      this.warning(
        "Very high delay values may cause unrealistic simulation results", 
        SmartCityPackage.Literals.DELAY_RANGE__MAX);
    }
  }

  @Check
  public void checkFrequencyNonNegative(final Frequency frequency) {
    int _value = frequency.getValue();
    boolean _lessEqualsThan = (_value <= 0);
    if (_lessEqualsThan) {
      this.error(
        "Frequency must be larger than 0", 
        SmartCityPackage.Literals.FREQUENCY__VALUE);
    }
  }

  @Check
  public void checkLinkDataTypeMatchesOriginIfSensor(final CommunicationLink link) {
    final Linkable origin = link.getOrigin();
    if ((origin instanceof Sensor)) {
      SensorType _type = ((Sensor)origin).getType();
      SensorType _datatype = link.getDatatype();
      boolean _notEquals = (!Objects.equals(_type, _datatype));
      if (_notEquals) {
        this.error(
          "For links from sensors the link data type must match the sensor type", 
          SmartCityPackage.Literals.COMMUNICATION_LINK__DATATYPE);
      }
    }
  }

  @Check
  public void checkCommunicationLinkDuplicates(final CommunicationLink link) {
    EObject _eContainer = link.eContainer();
    final Node node = ((Node) _eContainer);
    if ((node == null)) {
      return;
    }
    final Function1<CommunicationLink, Boolean> _function = (CommunicationLink otherLink) -> {
      return Boolean.valueOf((((((otherLink != link) && 
        Objects.equals(otherLink.getType(), link.getType())) && Objects.equals(otherLink.getOrigin(), link.getOrigin())) && 
        Objects.equals(otherLink.getDestination(), link.getDestination())) && Objects.equals(otherLink.getDatatype(), link.getDatatype())));
    };
    final Iterable<CommunicationLink> duplicates = IterableExtensions.<CommunicationLink>filter(node.getLinks(), _function);
    boolean _isEmpty = IterableExtensions.isEmpty(duplicates);
    boolean _not = (!_isEmpty);
    if (_not) {
      this.error(
        "Duplicate communication link", 
        null);
    }
  }

  @Check
  public void checkCommunicationLinkValidOrigin(final CommunicationLink link) {
    Linkable _origin = link.getOrigin();
    if ((_origin instanceof Controller)) {
      this.error("Controllers can\'t send data", 
        SmartCityPackage.Literals.COMMUNICATION_LINK__ORIGIN);
    } else {
      Linkable _origin_1 = link.getOrigin();
      if ((_origin_1 instanceof DataGateway)) {
        this.error("The DataGateway can\'t send data", 
          SmartCityPackage.Literals.COMMUNICATION_LINK__ORIGIN);
      }
    }
  }

  @Check
  public void checkCommunicationLinkValidDestination(final CommunicationLink link) {
    Linkable _destination = link.getDestination();
    if ((_destination instanceof Sensor)) {
      this.error("Sensors can\'t receive data", 
        SmartCityPackage.Literals.COMMUNICATION_LINK__DESTINATION);
    }
  }

  @Check
  public void checkCylicActionsHaveNotImplementedInfo(final CyclicAction action) {
    this.info(
      "Cyclic Actions are not yet implemented in the Code Generation, and will therefore have no effect for the simulation", 
      null);
  }

  @Check
  public void checkTriggeredActionsHaveNotImplementedInfo(final TriggeredAction action) {
    this.info(
      "Triggered Actions are not yet implemented in the Code Generator, and will therefore have no effect for the simulation", 
      null);
  }
}
