/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.validation;

import org.eclipse.xtext.validation.Check;
import uibk.ac.at.smartcity.smartCity.DataGateway;
import uibk.ac.at.smartcity.smartCity.Node;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmartCityValidator extends AbstractSmartCityValidator {
  protected static final String ISSUE_CODE_PREFIX = "uibk.ac.at.smartcity.";

  public static final String INVALID_ENTITY_NAME = "InvalidEntityName";

  public static final String INVALID_ATTRIBUTE_NAME = "InvalidAttributeName";

  @Check
  public void checkNodeStartsWithCapital(final Node node) {
    boolean _isLowerCase = Character.isLowerCase(node.getName().charAt(0));
    if (_isLowerCase) {
      this.warning("Node name should start with a capital", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ENTITY_NAME, 
        node.getName());
    }
  }

  @Check
  public void checkDataGatewayStartsWithCapital(final DataGateway dataGateway) {
    boolean _isLowerCase = Character.isLowerCase(dataGateway.getName().charAt(0));
    if (_isLowerCase) {
      this.warning("DataGateway name should start with a capital", 
        SmartCityPackage.Literals.LINKABLE__NAME, 
        SmartCityValidator.INVALID_ENTITY_NAME, 
        dataGateway.getName());
    }
  }
}
