/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uibk.ac.at.smartcity.smartCity.Controller;
import uibk.ac.at.smartcity.smartCity.ControllerType;
import uibk.ac.at.smartcity.smartCity.CyclicAction;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;
import uibk.ac.at.smartcity.smartCity.TriggeredAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Controller</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.ControllerImpl#getType <em>Type</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.ControllerImpl#getCyclicActions <em>Cyclic Actions</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.ControllerImpl#getTriggeredActions <em>Triggered Actions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ControllerImpl extends LinkableImpl implements Controller
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final ControllerType TYPE_EDEFAULT = ControllerType.ESP32;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected ControllerType type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getCyclicActions() <em>Cyclic Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCyclicActions()
   * @generated
   * @ordered
   */
  protected EList<CyclicAction> cyclicActions;

  /**
   * The cached value of the '{@link #getTriggeredActions() <em>Triggered Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTriggeredActions()
   * @generated
   * @ordered
   */
  protected EList<TriggeredAction> triggeredActions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ControllerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmartCityPackage.Literals.CONTROLLER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ControllerType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(ControllerType newType)
  {
    ControllerType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartCityPackage.CONTROLLER__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CyclicAction> getCyclicActions()
  {
    if (cyclicActions == null)
    {
      cyclicActions = new EObjectContainmentEList<CyclicAction>(CyclicAction.class, this, SmartCityPackage.CONTROLLER__CYCLIC_ACTIONS);
    }
    return cyclicActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TriggeredAction> getTriggeredActions()
  {
    if (triggeredActions == null)
    {
      triggeredActions = new EObjectContainmentEList<TriggeredAction>(TriggeredAction.class, this, SmartCityPackage.CONTROLLER__TRIGGERED_ACTIONS);
    }
    return triggeredActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmartCityPackage.CONTROLLER__CYCLIC_ACTIONS:
        return ((InternalEList<?>)getCyclicActions()).basicRemove(otherEnd, msgs);
      case SmartCityPackage.CONTROLLER__TRIGGERED_ACTIONS:
        return ((InternalEList<?>)getTriggeredActions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmartCityPackage.CONTROLLER__TYPE:
        return getType();
      case SmartCityPackage.CONTROLLER__CYCLIC_ACTIONS:
        return getCyclicActions();
      case SmartCityPackage.CONTROLLER__TRIGGERED_ACTIONS:
        return getTriggeredActions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmartCityPackage.CONTROLLER__TYPE:
        setType((ControllerType)newValue);
        return;
      case SmartCityPackage.CONTROLLER__CYCLIC_ACTIONS:
        getCyclicActions().clear();
        getCyclicActions().addAll((Collection<? extends CyclicAction>)newValue);
        return;
      case SmartCityPackage.CONTROLLER__TRIGGERED_ACTIONS:
        getTriggeredActions().clear();
        getTriggeredActions().addAll((Collection<? extends TriggeredAction>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.CONTROLLER__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case SmartCityPackage.CONTROLLER__CYCLIC_ACTIONS:
        getCyclicActions().clear();
        return;
      case SmartCityPackage.CONTROLLER__TRIGGERED_ACTIONS:
        getTriggeredActions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.CONTROLLER__TYPE:
        return type != TYPE_EDEFAULT;
      case SmartCityPackage.CONTROLLER__CYCLIC_ACTIONS:
        return cyclicActions != null && !cyclicActions.isEmpty();
      case SmartCityPackage.CONTROLLER__TRIGGERED_ACTIONS:
        return triggeredActions != null && !triggeredActions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //ControllerImpl
