/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uibk.ac.at.smartcity.smartCity.CyclicAction;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Module</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.ModuleImpl#getCyclicActions <em>Cyclic Actions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModuleImpl extends LinkableImpl implements uibk.ac.at.smartcity.smartCity.Module
{
  /**
   * The cached value of the '{@link #getCyclicActions() <em>Cyclic Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCyclicActions()
   * @generated
   * @ordered
   */
  protected EList<CyclicAction> cyclicActions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmartCityPackage.Literals.MODULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CyclicAction> getCyclicActions()
  {
    if (cyclicActions == null)
    {
      cyclicActions = new EObjectContainmentEList<CyclicAction>(CyclicAction.class, this, SmartCityPackage.MODULE__CYCLIC_ACTIONS);
    }
    return cyclicActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmartCityPackage.MODULE__CYCLIC_ACTIONS:
        return ((InternalEList<?>)getCyclicActions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmartCityPackage.MODULE__CYCLIC_ACTIONS:
        return getCyclicActions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmartCityPackage.MODULE__CYCLIC_ACTIONS:
        getCyclicActions().clear();
        getCyclicActions().addAll((Collection<? extends CyclicAction>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.MODULE__CYCLIC_ACTIONS:
        getCyclicActions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.MODULE__CYCLIC_ACTIONS:
        return cyclicActions != null && !cyclicActions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModuleImpl
