/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import uibk.ac.at.smartcity.smartCity.CommunicationLink;
import uibk.ac.at.smartcity.smartCity.Controller;
import uibk.ac.at.smartcity.smartCity.FrequencyUnit;
import uibk.ac.at.smartcity.smartCity.Node;
import uibk.ac.at.smartcity.smartCity.Sensor;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl#getSensors <em>Sensors</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl#getModules <em>Modules</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl#getController <em>Controller</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl#getFreqValue <em>Freq Value</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl#getFreqUnit <em>Freq Unit</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.NodeImpl#getLinks <em>Links</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NodeImpl extends LinkableImpl implements Node
{
  /**
   * The cached value of the '{@link #getSensors() <em>Sensors</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSensors()
   * @generated
   * @ordered
   */
  protected EList<Sensor> sensors;

  /**
   * The cached value of the '{@link #getModules() <em>Modules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModules()
   * @generated
   * @ordered
   */
  protected EList<uibk.ac.at.smartcity.smartCity.Module> modules;

  /**
   * The cached value of the '{@link #getController() <em>Controller</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getController()
   * @generated
   * @ordered
   */
  protected Controller controller;

  /**
   * The default value of the '{@link #getFreqValue() <em>Freq Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFreqValue()
   * @generated
   * @ordered
   */
  protected static final int FREQ_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getFreqValue() <em>Freq Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFreqValue()
   * @generated
   * @ordered
   */
  protected int freqValue = FREQ_VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getFreqUnit() <em>Freq Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFreqUnit()
   * @generated
   * @ordered
   */
  protected static final FrequencyUnit FREQ_UNIT_EDEFAULT = FrequencyUnit.HERTZ;

  /**
   * The cached value of the '{@link #getFreqUnit() <em>Freq Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFreqUnit()
   * @generated
   * @ordered
   */
  protected FrequencyUnit freqUnit = FREQ_UNIT_EDEFAULT;

  /**
   * The cached value of the '{@link #getLinks() <em>Links</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinks()
   * @generated
   * @ordered
   */
  protected EList<CommunicationLink> links;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmartCityPackage.Literals.NODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Sensor> getSensors()
  {
    if (sensors == null)
    {
      sensors = new EObjectContainmentEList<Sensor>(Sensor.class, this, SmartCityPackage.NODE__SENSORS);
    }
    return sensors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<uibk.ac.at.smartcity.smartCity.Module> getModules()
  {
    if (modules == null)
    {
      modules = new EObjectContainmentEList<uibk.ac.at.smartcity.smartCity.Module>(uibk.ac.at.smartcity.smartCity.Module.class, this, SmartCityPackage.NODE__MODULES);
    }
    return modules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Controller getController()
  {
    return controller;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetController(Controller newController, NotificationChain msgs)
  {
    Controller oldController = controller;
    controller = newController;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SmartCityPackage.NODE__CONTROLLER, oldController, newController);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setController(Controller newController)
  {
    if (newController != controller)
    {
      NotificationChain msgs = null;
      if (controller != null)
        msgs = ((InternalEObject)controller).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SmartCityPackage.NODE__CONTROLLER, null, msgs);
      if (newController != null)
        msgs = ((InternalEObject)newController).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SmartCityPackage.NODE__CONTROLLER, null, msgs);
      msgs = basicSetController(newController, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartCityPackage.NODE__CONTROLLER, newController, newController));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getFreqValue()
  {
    return freqValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFreqValue(int newFreqValue)
  {
    int oldFreqValue = freqValue;
    freqValue = newFreqValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartCityPackage.NODE__FREQ_VALUE, oldFreqValue, freqValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FrequencyUnit getFreqUnit()
  {
    return freqUnit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFreqUnit(FrequencyUnit newFreqUnit)
  {
    FrequencyUnit oldFreqUnit = freqUnit;
    freqUnit = newFreqUnit == null ? FREQ_UNIT_EDEFAULT : newFreqUnit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartCityPackage.NODE__FREQ_UNIT, oldFreqUnit, freqUnit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CommunicationLink> getLinks()
  {
    if (links == null)
    {
      links = new EObjectContainmentEList<CommunicationLink>(CommunicationLink.class, this, SmartCityPackage.NODE__LINKS);
    }
    return links;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SmartCityPackage.NODE__SENSORS:
        return ((InternalEList<?>)getSensors()).basicRemove(otherEnd, msgs);
      case SmartCityPackage.NODE__MODULES:
        return ((InternalEList<?>)getModules()).basicRemove(otherEnd, msgs);
      case SmartCityPackage.NODE__CONTROLLER:
        return basicSetController(null, msgs);
      case SmartCityPackage.NODE__LINKS:
        return ((InternalEList<?>)getLinks()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmartCityPackage.NODE__SENSORS:
        return getSensors();
      case SmartCityPackage.NODE__MODULES:
        return getModules();
      case SmartCityPackage.NODE__CONTROLLER:
        return getController();
      case SmartCityPackage.NODE__FREQ_VALUE:
        return getFreqValue();
      case SmartCityPackage.NODE__FREQ_UNIT:
        return getFreqUnit();
      case SmartCityPackage.NODE__LINKS:
        return getLinks();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmartCityPackage.NODE__SENSORS:
        getSensors().clear();
        getSensors().addAll((Collection<? extends Sensor>)newValue);
        return;
      case SmartCityPackage.NODE__MODULES:
        getModules().clear();
        getModules().addAll((Collection<? extends uibk.ac.at.smartcity.smartCity.Module>)newValue);
        return;
      case SmartCityPackage.NODE__CONTROLLER:
        setController((Controller)newValue);
        return;
      case SmartCityPackage.NODE__FREQ_VALUE:
        setFreqValue((Integer)newValue);
        return;
      case SmartCityPackage.NODE__FREQ_UNIT:
        setFreqUnit((FrequencyUnit)newValue);
        return;
      case SmartCityPackage.NODE__LINKS:
        getLinks().clear();
        getLinks().addAll((Collection<? extends CommunicationLink>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.NODE__SENSORS:
        getSensors().clear();
        return;
      case SmartCityPackage.NODE__MODULES:
        getModules().clear();
        return;
      case SmartCityPackage.NODE__CONTROLLER:
        setController((Controller)null);
        return;
      case SmartCityPackage.NODE__FREQ_VALUE:
        setFreqValue(FREQ_VALUE_EDEFAULT);
        return;
      case SmartCityPackage.NODE__FREQ_UNIT:
        setFreqUnit(FREQ_UNIT_EDEFAULT);
        return;
      case SmartCityPackage.NODE__LINKS:
        getLinks().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.NODE__SENSORS:
        return sensors != null && !sensors.isEmpty();
      case SmartCityPackage.NODE__MODULES:
        return modules != null && !modules.isEmpty();
      case SmartCityPackage.NODE__CONTROLLER:
        return controller != null;
      case SmartCityPackage.NODE__FREQ_VALUE:
        return freqValue != FREQ_VALUE_EDEFAULT;
      case SmartCityPackage.NODE__FREQ_UNIT:
        return freqUnit != FREQ_UNIT_EDEFAULT;
      case SmartCityPackage.NODE__LINKS:
        return links != null && !links.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (freqValue: ");
    result.append(freqValue);
    result.append(", freqUnit: ");
    result.append(freqUnit);
    result.append(')');
    return result.toString();
  }

} //NodeImpl
