/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uibk.ac.at.smartcity.smartCity.SimulationProperties;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simulation Properties</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.SimulationPropertiesImpl#getTerminationTime <em>Termination Time</em>}</li>
 *   <li>{@link uibk.ac.at.smartcity.smartCity.impl.SimulationPropertiesImpl#getGeneratorFile <em>Generator File</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimulationPropertiesImpl extends MinimalEObjectImpl.Container implements SimulationProperties
{
  /**
   * The default value of the '{@link #getTerminationTime() <em>Termination Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerminationTime()
   * @generated
   * @ordered
   */
  protected static final int TERMINATION_TIME_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTerminationTime() <em>Termination Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerminationTime()
   * @generated
   * @ordered
   */
  protected int terminationTime = TERMINATION_TIME_EDEFAULT;

  /**
   * The default value of the '{@link #getGeneratorFile() <em>Generator File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGeneratorFile()
   * @generated
   * @ordered
   */
  protected static final String GENERATOR_FILE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getGeneratorFile() <em>Generator File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGeneratorFile()
   * @generated
   * @ordered
   */
  protected String generatorFile = GENERATOR_FILE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimulationPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SmartCityPackage.Literals.SIMULATION_PROPERTIES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTerminationTime()
  {
    return terminationTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTerminationTime(int newTerminationTime)
  {
    int oldTerminationTime = terminationTime;
    terminationTime = newTerminationTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartCityPackage.SIMULATION_PROPERTIES__TERMINATION_TIME, oldTerminationTime, terminationTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getGeneratorFile()
  {
    return generatorFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGeneratorFile(String newGeneratorFile)
  {
    String oldGeneratorFile = generatorFile;
    generatorFile = newGeneratorFile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SmartCityPackage.SIMULATION_PROPERTIES__GENERATOR_FILE, oldGeneratorFile, generatorFile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SmartCityPackage.SIMULATION_PROPERTIES__TERMINATION_TIME:
        return getTerminationTime();
      case SmartCityPackage.SIMULATION_PROPERTIES__GENERATOR_FILE:
        return getGeneratorFile();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SmartCityPackage.SIMULATION_PROPERTIES__TERMINATION_TIME:
        setTerminationTime((Integer)newValue);
        return;
      case SmartCityPackage.SIMULATION_PROPERTIES__GENERATOR_FILE:
        setGeneratorFile((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.SIMULATION_PROPERTIES__TERMINATION_TIME:
        setTerminationTime(TERMINATION_TIME_EDEFAULT);
        return;
      case SmartCityPackage.SIMULATION_PROPERTIES__GENERATOR_FILE:
        setGeneratorFile(GENERATOR_FILE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SmartCityPackage.SIMULATION_PROPERTIES__TERMINATION_TIME:
        return terminationTime != TERMINATION_TIME_EDEFAULT;
      case SmartCityPackage.SIMULATION_PROPERTIES__GENERATOR_FILE:
        return GENERATOR_FILE_EDEFAULT == null ? generatorFile != null : !GENERATOR_FILE_EDEFAULT.equals(generatorFile);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (terminationTime: ");
    result.append(terminationTime);
    result.append(", generatorFile: ");
    result.append(generatorFile);
    result.append(')');
    return result.toString();
  }

} //SimulationPropertiesImpl
