/**
 * generated by Xtext 2.37.0
 */
package uibk.ac.at.smartcity.smartCity.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import uibk.ac.at.smartcity.smartCity.CommunicationLink;
import uibk.ac.at.smartcity.smartCity.Controller;
import uibk.ac.at.smartcity.smartCity.ControllerType;
import uibk.ac.at.smartcity.smartCity.CyclicAction;
import uibk.ac.at.smartcity.smartCity.DataGateway;
import uibk.ac.at.smartcity.smartCity.DataType;
import uibk.ac.at.smartcity.smartCity.DelayRange;
import uibk.ac.at.smartcity.smartCity.Frequency;
import uibk.ac.at.smartcity.smartCity.FrequencyUnit;
import uibk.ac.at.smartcity.smartCity.LinkType;
import uibk.ac.at.smartcity.smartCity.Linkable;
import uibk.ac.at.smartcity.smartCity.Model;
import uibk.ac.at.smartcity.smartCity.Node;
import uibk.ac.at.smartcity.smartCity.Sensor;
import uibk.ac.at.smartcity.smartCity.SensorType;
import uibk.ac.at.smartcity.smartCity.SimulationProperties;
import uibk.ac.at.smartcity.smartCity.SmartCityFactory;
import uibk.ac.at.smartcity.smartCity.SmartCityPackage;
import uibk.ac.at.smartcity.smartCity.TriggeredAction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class SmartCityFactoryImpl extends EFactoryImpl implements SmartCityFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static SmartCityFactory init()
  {
    try
    {
      SmartCityFactory theSmartCityFactory = (SmartCityFactory)EPackage.Registry.INSTANCE.getEFactory(SmartCityPackage.eNS_URI);
      if (theSmartCityFactory != null)
      {
        return theSmartCityFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new SmartCityFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SmartCityFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case SmartCityPackage.MODEL: return createModel();
      case SmartCityPackage.SIMULATION_PROPERTIES: return createSimulationProperties();
      case SmartCityPackage.DATA_GATEWAY: return createDataGateway();
      case SmartCityPackage.NODE: return createNode();
      case SmartCityPackage.SENSOR: return createSensor();
      case SmartCityPackage.COMMUNICATION_LINK: return createCommunicationLink();
      case SmartCityPackage.CONTROLLER: return createController();
      case SmartCityPackage.MODULE: return createModule();
      case SmartCityPackage.FREQUENCY: return createFrequency();
      case SmartCityPackage.LINKABLE: return createLinkable();
      case SmartCityPackage.DELAY_RANGE: return createDelayRange();
      case SmartCityPackage.CYCLIC_ACTION: return createCyclicAction();
      case SmartCityPackage.TRIGGERED_ACTION: return createTriggeredAction();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case SmartCityPackage.SENSOR_TYPE:
        return createSensorTypeFromString(eDataType, initialValue);
      case SmartCityPackage.CONTROLLER_TYPE:
        return createControllerTypeFromString(eDataType, initialValue);
      case SmartCityPackage.LINK_TYPE:
        return createLinkTypeFromString(eDataType, initialValue);
      case SmartCityPackage.DATA_TYPE:
        return createDataTypeFromString(eDataType, initialValue);
      case SmartCityPackage.FREQUENCY_UNIT:
        return createFrequencyUnitFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case SmartCityPackage.SENSOR_TYPE:
        return convertSensorTypeToString(eDataType, instanceValue);
      case SmartCityPackage.CONTROLLER_TYPE:
        return convertControllerTypeToString(eDataType, instanceValue);
      case SmartCityPackage.LINK_TYPE:
        return convertLinkTypeToString(eDataType, instanceValue);
      case SmartCityPackage.DATA_TYPE:
        return convertDataTypeToString(eDataType, instanceValue);
      case SmartCityPackage.FREQUENCY_UNIT:
        return convertFrequencyUnitToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimulationProperties createSimulationProperties()
  {
    SimulationPropertiesImpl simulationProperties = new SimulationPropertiesImpl();
    return simulationProperties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DataGateway createDataGateway()
  {
    DataGatewayImpl dataGateway = new DataGatewayImpl();
    return dataGateway;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Node createNode()
  {
    NodeImpl node = new NodeImpl();
    return node;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sensor createSensor()
  {
    SensorImpl sensor = new SensorImpl();
    return sensor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CommunicationLink createCommunicationLink()
  {
    CommunicationLinkImpl communicationLink = new CommunicationLinkImpl();
    return communicationLink;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Controller createController()
  {
    ControllerImpl controller = new ControllerImpl();
    return controller;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public uibk.ac.at.smartcity.smartCity.Module createModule()
  {
    ModuleImpl module = new ModuleImpl();
    return module;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Frequency createFrequency()
  {
    FrequencyImpl frequency = new FrequencyImpl();
    return frequency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Linkable createLinkable()
  {
    LinkableImpl linkable = new LinkableImpl();
    return linkable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DelayRange createDelayRange()
  {
    DelayRangeImpl delayRange = new DelayRangeImpl();
    return delayRange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CyclicAction createCyclicAction()
  {
    CyclicActionImpl cyclicAction = new CyclicActionImpl();
    return cyclicAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TriggeredAction createTriggeredAction()
  {
    TriggeredActionImpl triggeredAction = new TriggeredActionImpl();
    return triggeredAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SensorType createSensorTypeFromString(EDataType eDataType, String initialValue)
  {
    SensorType result = SensorType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertSensorTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ControllerType createControllerTypeFromString(EDataType eDataType, String initialValue)
  {
    ControllerType result = ControllerType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertControllerTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LinkType createLinkTypeFromString(EDataType eDataType, String initialValue)
  {
    LinkType result = LinkType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertLinkTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType createDataTypeFromString(EDataType eDataType, String initialValue)
  {
    DataType result = DataType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertDataTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FrequencyUnit createFrequencyUnitFromString(EDataType eDataType, String initialValue)
  {
    FrequencyUnit result = FrequencyUnit.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertFrequencyUnitToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SmartCityPackage getSmartCityPackage()
  {
    return (SmartCityPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static SmartCityPackage getPackage()
  {
    return SmartCityPackage.eINSTANCE;
  }

} //SmartCityFactoryImpl
